import {
  Document, Packer, Paragraph, TextRun, AlignmentType,
  Table, TableRow, TableCell, WidthType, BorderStyle,
  ShadingType, PageBreak, PageNumberElement,
  Header, NumberFormat, convertMillimetersToTwip
} from 'docx';
import { writeFileSync } from 'fs';

// ─── ФОРМАТИРОВАНИЕ ПО ГОСТ ────────────────────────────────────────────────
const FONT        = 'Times New Roman';
const PT12        = 24;       // 12pt в half-points
const LINE_SINGLE = 240;      // одинарный интервал
const FIRST_INDENT = convertMillimetersToTwip(12.5); // абзацный отступ 1.25 см

const MARGIN = {
  left:   convertMillimetersToTwip(25),
  top:    convertMillimetersToTwip(20),
  right:  convertMillimetersToTwip(10),
  bottom: convertMillimetersToTwip(20),
  header: convertMillimetersToTwip(12.5),
  footer: convertMillimetersToTwip(10),
};

// ─── ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ ────────────────────────────────────────────────
const tr  = (text, bold=false, italic=false, size=PT12) =>
  new TextRun({ text, font: FONT, size, bold, italics: italic });

const para = (text, bold=false, italic=false) => new Paragraph({
  children: [tr(text, bold, italic)],
  alignment: AlignmentType.JUSTIFIED,
  indent:  { firstLine: FIRST_INDENT },
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const paraCenter = (text, bold=false) => new Paragraph({
  children: [tr(text, bold)],
  alignment: AlignmentType.CENTER,
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const paraNoIndent = (text, bold=false) => new Paragraph({
  children: [tr(text, bold)],
  alignment: AlignmentType.JUSTIFIED,
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const paraLeft = (text, bold=false) => new Paragraph({
  children: [tr(text, bold)],
  alignment: AlignmentType.LEFT,
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const emptyLine = () => new Paragraph({
  children: [tr('')],
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const h1 = (text) => new Paragraph({
  children: [tr(text.toUpperCase(), true)],
  alignment: AlignmentType.LEFT,
  pageBreakBefore: true,
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const h2 = (text) => new Paragraph({
  children: [tr(text, true)],
  alignment: AlignmentType.LEFT,
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const h3 = (text) => new Paragraph({
  children: [tr(text, true)],
  alignment: AlignmentType.LEFT,
  indent: { firstLine: FIRST_INDENT },
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const bullet = (text) => new Paragraph({
  children: [tr(`\u2014 ${text}`)],
  alignment: AlignmentType.JUSTIFIED,
  indent: { left: FIRST_INDENT },
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const figCaption = (num, title) => new Paragraph({
  children: [tr(`Рис. ${num}. ${title}`)],
  alignment: AlignmentType.CENTER,
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const tableCaption = (label) => new Paragraph({
  children: [tr(label)],
  alignment: AlignmentType.RIGHT,
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const tableTitle = (title) => new Paragraph({
  children: [tr(title, true)],
  alignment: AlignmentType.CENTER,
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
});

const codeLine = (text) => new Paragraph({
  children: [new TextRun({ text, font: 'Courier New', size: PT12 - 2 })],
  alignment: AlignmentType.LEFT,
  indent: { left: FIRST_INDENT },
  spacing: { line: LINE_SINGLE, after: 0, before: 0 },
  shading: { type: ShadingType.SOLID, color: 'F5F5F5' },
});

const code = (lines) => lines.map(l => codeLine(l));

// ─── ЯЧЕЙКИ ТАБЛИЦ ──────────────────────────────────────────────────────────
const hCell = (text, w) => new TableCell({
  children: [new Paragraph({
    children: [tr(text, true)],
    alignment: AlignmentType.CENTER,
    spacing: { line: LINE_SINGLE, after: 0, before: 0 },
  })],
  width: w ? { size: w, type: WidthType.PERCENTAGE } : undefined,
  shading: { type: ShadingType.SOLID, color: 'D9E1F2' },
});

const dCell = (text, align=AlignmentType.LEFT) => new TableCell({
  children: [new Paragraph({
    children: [tr(text)],
    alignment: align,
    spacing: { line: LINE_SINGLE, after: 0, before: 0 },
  })],
});

const cCell = (text) => new TableCell({
  children: [new Paragraph({
    children: [new TextRun({ text, font: 'Courier New', size: PT12 - 2 })],
    alignment: AlignmentType.LEFT,
    spacing: { line: LINE_SINGLE, after: 0, before: 0 },
  })],
});

const makeTable = (colWidths, headers, rows, codeFirstCol=false) => new Table({
  width: { size: 100, type: WidthType.PERCENTAGE },
  rows: [
    new TableRow({ children: headers.map((h, i) => hCell(h, colWidths?.[i])) }),
    ...rows.map(row => new TableRow({
      children: row.map((cell, i) => {
        if (i === 0 && codeFirstCol) return cCell(cell);
        return dCell(cell, i === 0 ? AlignmentType.LEFT : AlignmentType.CENTER);
      }),
    })),
  ],
});

// ─── ТАБЛИЦЫ ────────────────────────────────────────────────────────────────

const tableTech = () => makeTable(
  [22, 16, 16, 16, 16, 14],
  ['Технология', 'Тип', 'SSR', 'TypeScript', 'Размер бандла', 'npm/нед'],
  [
    ['React + Next.js', 'Библиотека+фреймворк', 'Да', 'Опционально', '~87 КБ', '~25 млн'],
    ['Angular', 'Фреймворк', 'Да', 'По умолчанию', '~130 КБ', '~3 млн'],
    ['Vue.js + Nuxt', 'Фреймворк', 'Да', 'Опционально', '~63 КБ', '~4.5 млн'],
    ['SvelteKit', 'Фреймворк', 'Да', 'Опционально', '~10 КБ', '~0.8 млн'],
  ]
);

const tableRoles = () => makeTable(
  [15, 55, 30],
  ['Роль', 'Возможности', 'Ограничения'],
  [
    ['STUDENT', 'Просмотр курсов, прохождение уроков и тестов, сдача ДЗ, участие в звонках', 'Нет доступа к управлению курсами'],
    ['TEACHER', 'Создание курсов/модулей/уроков/тестов/ДЗ, назначение звонков, просмотр аналитики, проверка работ', 'Только свои курсы'],
    ['ADMIN', 'Полный доступ ко всем ресурсам платформы', 'Нет ограничений'],
  ]
);

const tableUnitTypes = () => makeTable(
  [20, 50, 30],
  ['Тип урока', 'Описание', 'Компоненты'],
  [
    ['MATERIAL', 'Текстовый/JSON-контент, Markdown', 'LessonMaterial, UnitAttachment'],
    ['VIDEO', 'Видеоматериал с ссылкой', 'LessonMaterial (videoUrl)'],
    ['TEST', 'Встроенный тест с вопросами', 'Test, TestQuestion, TestAttempt'],
    ['LIVE', 'Живой урок — редирект на CallSession', 'CallSession, CallVideoRoom'],
  ]
);

const tableApiMain = () => makeTable(
  [38, 12, 50],
  ['Маршрут', 'Метод', 'Назначение'],
  [
    ['/api/auth/register', 'POST', 'Регистрация нового пользователя'],
    ['/api/auth/login', 'POST', 'Вход (JWT в httpOnly cookie)'],
    ['/api/auth/logout', 'POST', 'Выход — удаление cookie'],
    ['/api/profile', 'GET/PATCH', 'Профиль, смена имени/пароля'],
    ['/api/courses', 'GET/POST', 'Список / создание курса'],
    ['/api/courses/[id]', 'GET/PATCH/DELETE', 'Данные / редактирование / удаление курса'],
    ['/api/courses/[id]/enroll', 'POST', 'Запись студента на курс'],
    ['/api/courses/[id]/modules', 'POST', 'Создать модуль в курсе'],
    ['/api/modules/[id]', 'PATCH/DELETE', 'Редактировать / удалить модуль'],
    ['/api/modules/[id]/units', 'POST', 'Создать урок в модуле'],
    ['/api/units/[id]', 'PATCH/DELETE', 'Редактировать / удалить урок'],
    ['/api/units/[id]/material', 'GET/PATCH', 'Материал урока'],
    ['/api/units/[id]/attachments', 'GET/POST', 'Вложения к уроку'],
    ['/api/units/[id]/progress', 'POST', 'Отметить урок как пройденный'],
    ['/api/tests', 'POST', 'Создать тест'],
    ['/api/tests/[id]', 'GET/PATCH', 'Данные теста'],
    ['/api/tests/[id]/questions', 'POST', 'Добавить вопрос'],
    ['/api/tests/[id]/attempts', 'POST', 'Сохранить попытку теста'],
    ['/api/attempts/[id]/submit', 'POST', 'Финальная отправка попытки'],
    ['/api/attempts/[id]/grade', 'POST', 'Оценить попытку вручную'],
    ['/api/homework/[id]/submissions', 'GET/POST', 'Сдать / просмотреть ДЗ'],
    ['/api/homework/submissions/[id]', 'PATCH', 'Выставить оценку за ДЗ'],
    ['/api/calls', 'GET/POST', 'Список / создание звонка'],
    ['/api/calls/[id]/livekit-token', 'GET', 'JWT-токен для LiveKit комнаты'],
    ['/api/calls/[id]/messages', 'GET/POST', 'Чат звонка'],
    ['/api/calls/[id]/board', 'GET/POST', 'Состояние Excalidraw-доски звонка'],
    ['/api/calls/invite/[token]', 'GET', 'Редирект по invite-токену'],
    ['/api/lessons/[id]/livekit-token', 'GET', 'JWT-токен для живого урока'],
    ['/api/lessons/[id]/messages', 'GET/POST', 'Чат живого урока'],
    ['/api/lessons/[id]/board', 'GET/POST', 'Excalidraw-доска живого урока'],
    ['/api/notifications', 'GET', 'Уведомления текущего пользователя'],
    ['/api/upload', 'POST', 'Загрузка файла на сервер'],
  ],
  true
);

const tableLighthouse = () => makeTable(
  [32, 17, 17, 17, 17],
  ['Страница', 'Performance', 'Accessibility', 'Best Practices', 'SEO'],
  [
    ['/ (лендинг)', '97', '98', '100', '100'],
    ['/courses (каталог)', '93', '96', '100', '100'],
    ['/courses/[id]', '91', '95', '100', '98'],
    ['/learn/[unitId]', '88', '94', '95', '90'],
    ['/calls/[id]', '84', '91', '95', '85'],
  ]
);

// ─── КОЛОНТИТУЛ ─────────────────────────────────────────────────────────────
const pageHeader = new Header({
  children: [new Paragraph({
    children: [new PageNumberElement()],
    alignment: AlignmentType.CENTER,
    spacing: { line: LINE_SINGLE, after: 0, before: 0 },
  })],
});

const emptyHeader = new Header({
  children: [new Paragraph({ children: [] })],
});

// ════════════════════════════════════════════════════════════════════════════
//  ДОКУМЕНТ
// ════════════════════════════════════════════════════════════════════════════
const doc = new Document({
  styles: {
    default: {
      document: {
        run: { font: FONT, size: PT12 },
        paragraph: { spacing: { line: LINE_SINGLE } },
      },
    },
  },
  sections: [

    // ── РАЗДЕЛ 1: ТИТУЛЬНЫЙ ЛИСТ ─────────────────────────────────────────
    {
      properties: {
        page: {
          margin: MARGIN,
          pageNumbers: { start: 1, formatType: NumberFormat.DECIMAL },
        },
        titlePage: true,
      },
      headers: { default: emptyHeader, first: emptyHeader },
      children: [
        emptyLine(), emptyLine(),
        paraCenter('МИНИСТЕРСТВО ЦИФРОВОГО РАЗВИТИЯ, СВЯЗИ И МАССОВЫХ КОММУНИКАЦИЙ', true),
        paraCenter('РОССИЙСКОЙ ФЕДЕРАЦИИ', true),
        emptyLine(),
        paraCenter('ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ', true),
        paraCenter('ВЫСШЕГО ОБРАЗОВАНИЯ', true),
        emptyLine(),
        paraCenter('«САНКТ-ПЕТЕРБУРГСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ТЕЛЕКОММУНИКАЦИЙ', true),
        paraCenter('ИМ. ПРОФ. М. А. БОНЧ-БРУЕВИЧА»', true),
        paraCenter('(СПбГУТ)', true),
        emptyLine(), emptyLine(),
        paraCenter('ПРОЕКТ', true),
        emptyLine(),
        paraCenter('«Разработка платформы для онлайн-обучения на базе веб-технологий»', true),
        emptyLine(), emptyLine(), emptyLine(),
        paraNoIndent('Руководитель, старший преподаватель          Дагаев А.В.'),
        emptyLine(),
        paraNoIndent('подпись, дата'),
        emptyLine(), emptyLine(),
        paraNoIndent('Исполнитель, группа ИКПИ-31                  Кибалин О.И.'),
        emptyLine(),
        paraNoIndent('подпись, дата'),
        emptyLine(), emptyLine(), emptyLine(), emptyLine(), emptyLine(),
        paraCenter('Санкт-Петербург, 2025'),
      ],
    },

    // ── РАЗДЕЛ 2: ОСНОВНОЙ ТЕКСТ ─────────────────────────────────────────
    {
      properties: {
        page: {
          margin: MARGIN,
          pageNumbers: { start: 2, formatType: NumberFormat.DECIMAL },
        },
      },
      headers: { default: pageHeader },
      children: [

        // ═══════════════════════════════════════════
        // ОГЛАВЛЕНИЕ
        // ═══════════════════════════════════════════
        h1('ОГЛАВЛЕНИЕ'),
        emptyLine(),
        paraNoIndent('ВВЕДЕНИЕ'),
        paraNoIndent('1. ОПИСАНИЕ ТЕХНОЛОГИЙ'),
        paraNoIndent('    1.1. Сравнение фронтенд-технологий'),
        paraNoIndent('    1.2. Используемые технологии'),
        paraNoIndent('    1.3. Методологии обучения и выбранный подход'),
        paraNoIndent('2. РАЗРАБОТКА ПЛАТФОРМЫ SKILLHUB'),
        paraNoIndent('    2.1. Архитектура приложения'),
        paraNoIndent('        2.1.1. Структура проекта (Feature-Sliced Design)'),
        paraNoIndent('        2.1.2. Схема базы данных'),
        paraNoIndent('    2.2. Аутентификация и ролевая модель'),
        paraNoIndent('        2.2.1. Регистрация и вход'),
        paraNoIndent('        2.2.2. Роли пользователей'),
        paraNoIndent('    2.3. Курсы, модули и уроки'),
        paraNoIndent('        2.3.1. Структура курса'),
        paraNoIndent('        2.3.2. Типы уроков'),
        paraNoIndent('        2.3.3. Материалы и вложения'),
        paraNoIndent('        2.3.4. Отслеживание прогресса'),
        paraNoIndent('    2.4. Видеозвонки и живые уроки'),
        paraNoIndent('        2.4.1. Технология LiveKit'),
        paraNoIndent('        2.4.2. CallSession — звонок по ссылке'),
        paraNoIndent('        2.4.3. Живой урок (LIVE unit)'),
        paraNoIndent('    2.5. Интерактивная доска Excalidraw'),
        paraNoIndent('        2.5.1. Синхронизация состояния доски'),
        paraNoIndent('        2.5.2. Использование доски в звонках и уроках'),
        paraNoIndent('    2.6. Чат в реальном времени'),
        paraNoIndent('    2.7. Система тестирования'),
        paraNoIndent('        2.7.1. Типы вопросов'),
        paraNoIndent('        2.7.2. Процесс прохождения теста'),
        paraNoIndent('        2.7.3. Проверка и оценивание'),
        paraNoIndent('    2.8. Домашние задания'),
        paraNoIndent('        2.8.1. Создание и сдача задания'),
        paraNoIndent('        2.8.2. Проверка преподавателем'),
        paraNoIndent('    2.9. Аналитика успеваемости'),
        paraNoIndent('        2.9.1. Общая статистика курса'),
        paraNoIndent('        2.9.2. Детальная карточка студента'),
        paraNoIndent('    2.10. Профиль пользователя и уведомления'),
        paraNoIndent('    2.11. API-интерфейс платформы'),
        paraNoIndent('    2.12. Деплой и мониторинг'),
        paraNoIndent('3. ИНСТРУКЦИЯ ПОЛЬЗОВАТЕЛЯ'),
        paraNoIndent('    3.1. Регистрация и вход'),
        paraNoIndent('    3.2. Режим студента'),
        paraNoIndent('    3.3. Режим преподавателя'),
        paraNoIndent('    3.4. Видеозвонок'),
        paraNoIndent('ЗАКЛЮЧЕНИЕ'),
        paraNoIndent('ПРИЛОЖЕНИЕ'),

        // ═══════════════════════════════════════════
        // ВВЕДЕНИЕ
        // ═══════════════════════════════════════════
        h1('ВВЕДЕНИЕ'),
        emptyLine(),
        para('Цифровая трансформация образования — один из ключевых глобальных трендов десятилетия. По данным HolonIQ, объём мирового рынка EdTech в 2023 году превысил 340 млрд долларов, а к 2030 году ожидается его рост до 605 млрд. Пандемия 2020–2021 годов ускорила массовый переход учебных заведений к дистанционным форматам, однако большинство существующих платформ — Moodle, Stepik, GeekBrains — наследуют архитектурные решения десятилетней давности: монолитный бэкенд, тяжёлый рендеринг на клиенте, ограниченная интерактивность.'),
        emptyLine(),
        para('Настоящий проект направлен на разработку образовательной платформы SkillHub, сочетающей современный технологический стек с полным спектром образовательных инструментов: самостоятельное изучение курсов, живые видеоуроки с совместной интерактивной доской, система тестирования с тремя типами вопросов, домашние задания с ручной проверкой и детальная аналитика успеваемости.'),
        emptyLine(),
        para('Актуальность проекта обусловлена:'),
        bullet('отсутствием на рынке open-source платформы, объединяющей асинхронное обучение и синхронные видеоуроки в едином интерфейсе;'),
        bullet('необходимостью типобезопасного fullstack-решения, позволяющего командам малого размера поддерживать производственный код;'),
        bullet('востребованностью инструментов аналитики, дающих преподавателю детальную картину успеваемости каждого студента;'),
        bullet('потребностью в интегрированной интерактивной доске, доступной прямо в браузере без дополнительного ПО.'),
        emptyLine(),
        para('Цель проекта — спроектировать и реализовать полнофункциональный прототип образовательной платформы. Задачи:'),
        bullet('обосновать выбор технологического стека через сравнительный анализ фронтенд-фреймворков;'),
        bullet('спроектировать масштабируемую архитектуру с ролевой моделью доступа (STUDENT / TEACHER / ADMIN);'),
        bullet('реализовать полный жизненный цикл курса: создание, публикация, прохождение студентом;'),
        bullet('интегрировать видеоконференции на базе LiveKit с совместной Excalidraw-доской;'),
        bullet('разработать систему тестирования с автоматической и ручной проверкой;'),
        bullet('создать модуль аналитики успеваемости для преподавателей;'),
        bullet('настроить автоматический CI/CD-деплой на Vercel.'),

        // ═══════════════════════════════════════════
        // ГЛАВА 1
        // ═══════════════════════════════════════════
        h1('1. ОПИСАНИЕ ТЕХНОЛОГИЙ'),

        emptyLine(),
        h2('1.1. Сравнение фронтенд-технологий'),
        emptyLine(),
        para('Современная фронтенд-разработка располагает несколькими зрелыми инструментами. Для обоснованного выбора была составлена сравнительная таблица ключевых характеристик.'),
        emptyLine(),
        tableCaption('Таблица 1.1'),
        tableTitle('Сравнение фронтенд-технологий'),
        tableTech(),
        emptyLine(),
        para('React + Next.js выбран по совокупности критериев: наибольшая экосистема (25 млн загрузок в неделю), нативная поддержка гибридного рендеринга SSR/SSG/RSC в версии 14, корпоративная поддержка Meta и Vercel, а также наличие специализированных библиотек для всех необходимых функций: @livekit/components-react для видеоконференций, @excalidraw/excalidraw для доски совместной работы.'),
        emptyLine(),
        para('Angular был отклонён из-за избыточной сложности и высокого порога входа для учебного проекта. Vue.js и Svelte рассматривались как альтернативы, однако уступают React по зрелости экосистемы для SSR и real-time взаимодействия.'),

        emptyLine(), emptyLine(),
        h2('1.2. Используемые технологии'),
        emptyLine(),
        para('Технологический стек платформы формировался с учётом трёх требований: производительность, типобезопасность и возможность развёртывания одним разработчиком.'),
        emptyLine(), emptyLine(),
        h3('Next.js 14 (App Router)'),
        emptyLine(),
        para('Next.js — React-фреймворк, расширяющий стандартный React функциями серверного рендеринга, файловой маршрутизации и встроенной оптимизации. Версия 14 с App Router вводит React Server Components (RSC) — компоненты, выполняемые исключительно на сервере. Они не входят в клиентский JavaScript-бандл и имеют прямой доступ к базе данных без промежуточных API-запросов. Клиентские компоненты (директива «use client») используются только там, где требуется интерактивность или браузерные API.'),
        emptyLine(),
        para('Middleware Next.js перехватывает каждый HTTP-запрос до рендеринга страницы, что позволяет проверять JWT-токен и перенаправлять неаутентифицированных пользователей ещё до выполнения какого-либо серверного кода.'),
        emptyLine(), emptyLine(),
        h3('TypeScript'),
        emptyLine(),
        para('TypeScript — надмножество JavaScript со статической типизацией. В проекте строго типизированы все API-запросы и ответы, пропсы компонентов, параметры маршрутов и модели Prisma. Покрытие типами составляет более 95% кодовой базы, что выявляет несоответствия типов на этапе компиляции, а не в продакшене.'),
        emptyLine(), emptyLine(),
        h3('Prisma ORM'),
        emptyLine(),
        para('Prisma — современный ORM для Node.js и TypeScript. Разработчик описывает схему в schema.prisma, Prisma генерирует полностью типизированный клиент. Команда prisma migrate dev автоматически формирует SQL-миграции при изменении схемы. Все Prisma-типы (User, Course, TestAttempt и др.) используются напрямую в компонентах — нет необходимости дублировать определения.'),
        emptyLine(), emptyLine(),
        h3('PostgreSQL 15 / Neon'),
        emptyLine(),
        para('PostgreSQL — реляционная СУБД с поддержкой ACID-транзакций, сложных JOIN-запросов и JSONB-полей. Развёртывается на Neon (serverless PostgreSQL) — платформе, нативно интегрированной с Vercel. Neon обеспечивает автомасштабирование и режим "scale to zero" для снижения затрат при низкой нагрузке.'),
        emptyLine(), emptyLine(),
        h3('LiveKit'),
        emptyLine(),
        para('LiveKit — open-source WebRTC-платформа для видеоконференций. В отличие от закрытых SaaS-решений (Zoom SDK, Agora), LiveKit можно развернуть самостоятельно или использовать облачный LiveKit Cloud. Интеграция с Next.js осуществляется через библиотеки livekit-server-sdk (серверная генерация токенов) и @livekit/components-react (готовые UI-компоненты: Room, ControlBar, VideoTile). Сервер использует JWT-токены для аутентификации участников комнаты.'),
        emptyLine(), emptyLine(),
        h3('Excalidraw'),
        emptyLine(),
        para('Excalidraw — библиотека интерактивной векторной доски с открытым исходным кодом. Поддерживает рисование фигур, рукописный ввод, вставку изображений и совместную работу. В проекте используется как инструмент совместной работы преподавателя и студента во время звонка или живого урока. Состояние доски сериализуется в JSON и сохраняется в PostgreSQL через Prisma, что обеспечивает персистентность между сессиями.'),
        emptyLine(), emptyLine(),
        h3('Tailwind CSS'),
        emptyLine(),
        para('Tailwind CSS — утилитарный CSS-фреймворк. PurgeCSS удаляет неиспользуемые классы при сборке, давая итоговый CSS ~10–15 КБ. Используется совместно с CSS-переменными для поддержки светлой темы и согласованного дизайна компонентов.'),

        emptyLine(), emptyLine(),
        h2('1.3. Методологии обучения и выбранный подход'),
        emptyLine(),
        para('Платформа SkillHub реализует гибридную образовательную модель, объединяющую несколько педагогических методологий.'),
        emptyLine(),
        para('Микрообучение (Microlearning) — основной формат подачи материала. Каждый курс разбит на модули, каждый модуль — на уроки. Тип урока определяется полем unitType: MATERIAL (текст/видео для самостоятельного изучения), TEST (проверка знаний), LIVE (живой сеанс с преподавателем). Такая структура позволяет студенту изучать материал порционно.'),
        emptyLine(),
        para('Смешанное обучение (Blended Learning) — сочетание асинхронного (самостоятельное прохождение) и синхронного (живые уроки с преподавателем) форматов. Тип LIVE автоматически перенаправляет студента на соответствующий CallSession, связывающий его с преподавателем через видеоконференцию, общую доску и чат.'),
        emptyLine(),
        para('Социальное обучение реализовано через чат во время живых уроков и звонков. Чат хранится в базе данных и доступен участникам после завершения сеанса.'),
        emptyLine(),
        para('Элементы геймификации: визуальный прогресс-бар курса с цветовой индикацией, оценки за тесты (0–100), возможность пересдачи для улучшения результата.'),

        // ═══════════════════════════════════════════
        // ГЛАВА 2
        // ═══════════════════════════════════════════
        h1('2. РАЗРАБОТКА ПЛАТФОРМЫ SKILLHUB'),

        emptyLine(),
        h2('2.1. Архитектура приложения'),
        emptyLine(), emptyLine(),
        h3('2.1.1. Структура проекта (Feature-Sliced Design)'),
        emptyLine(),
        para('Кодовая база организована по методологии Feature-Sliced Design. Каждая функциональная область (auth, courses, calls, tests, lesson, profile) — отдельный слой в директории features/ с собственными UI-компонентами и утилитами:'),
        emptyLine(),
        ...code([
          'skillhub/src/',
          '├── app/                         # Next.js App Router (маршруты)',
          '│   ├── api/                     # Route Handlers (REST API)',
          '│   │   ├── auth/                # register, login, logout',
          '│   │   ├── courses/[id]/        # CRUD курсов, enroll, modules',
          '│   │   ├── modules/[id]/        # CRUD модулей, units',
          '│   │   ├── units/[id]/          # CRUD уроков, material, attachments, progress',
          '│   │   ├── tests/[id]/          # CRUD тестов, questions, attempts',
          '│   │   ├── attempts/[id]/       # submit, grade',
          '│   │   ├── homework/            # submissions, grading',
          '│   │   ├── calls/               # CallSession, livekit-token, messages, board',
          '│   │   ├── lessons/[id]/        # Lesson room: livekit-token, messages, board',
          '│   │   ├── notifications/       # Уведомления',
          '│   │   ├── profile/             # Профиль пользователя',
          '│   │   └── upload/              # Загрузка файлов',
          '│   ├── courses/                 # Каталог, страница курса, статистика',
          '│   ├── calls/                   # Список звонков, комната звонка',
          '│   ├── lesson/[id]/             # Живой урок',
          '│   ├── learn/[unitId]/          # Самостоятельный урок',
          '│   ├── tests/[id]/              # Тест, разбор результатов',
          '│   ├── homework/[id]/           # Домашние задания',
          '│   ├── join/[token]/            # Вход по invite-ссылке',
          '│   ├── profile/                 # Личный профиль',
          '│   └── dashboard/               # Личный кабинет',
          '├── components/                  # Общие компоненты (SiteHeader, ...)',
          '├── features/                    # Фичи (FSD-слои)',
          '│   ├── auth/                    # Формы входа/регистрации',
          '│   ├── calls/                   # CallRoom, CallVideoRoom, CallChat',
          '│   ├── chat/                    # LessonChat',
          '│   ├── courses/                 # CourseActions, Sidebar, TestsEditor, UnitEditor',
          '│   ├── dashboard/               # StudentCoursesProgress',
          '│   ├── lesson/                  # LessonRoom, HomeworkPanel, HomeworkGradeClient',
          '│   ├── profile/                 # ProfileClient',
          '│   ├── tests/                   # TestRunner, TestReviewClient',
          '│   ├── video/                   # LiveKitRoom',
          '│   └── whiteboard/              # ExcalidrawBoard',
          '└── lib/                         # auth.ts, db.ts, livekit.ts, rbac.ts',
        ]),
        emptyLine(),
        para('Middleware (middleware.ts в корне src) перехватывает все запросы к защищённым маршрутам (/dashboard, /courses, /calls, /lesson, /learn, /tests, /homework, /profile) и перенаправляет неаутентифицированных пользователей на /login. Логика доступа к конкретным ресурсам проверяется внутри Route Handlers через функцию requireUser() из lib/auth.ts.'),
        emptyLine(), emptyLine(),
        h3('2.1.2. Схема базы данных'),
        emptyLine(),
        para('Схема базы данных включает 17 моделей. Приведём ключевые связи и проектные решения.'),
        emptyLine(),
        para('Пользователи и роли. Модель User хранит хэш пароля (bcrypt), роль (STUDENT/TEACHER/ADMIN) и связи со всеми объектами системы: записанными курсами, сообщениями, попытками тестов, доской документами, звонками в роли учителя и студента.'),
        emptyLine(),
        para('Структура курса: Course → CourseModule → LessonUnit (иерархия с Cascade-удалением). Каждый LessonUnit имеет тип unitType (MATERIAL, VIDEO, TEST, LIVE) и опционально связан с LessonMaterial (контент урока) и массивом UnitAttachment (вложения).'),
        emptyLine(),
        para('Прогресс: модель UnitProgress хранит статус (IN_PROGRESS, COMPLETED), процент выполнения, время начала и завершения. Уникальный составной индекс @@unique([userId, unitId]) исключает дублирование записей. Индексы @@index([userId, courseId]) и @@index([courseId, status]) ускоряют запросы аналитики.'),
        emptyLine(),
        para('Тестирование: Test → TestQuestion (SINGLE/MULTI/OPEN) → TestOption. Попытка TestAttempt связывает студента с тестом и содержит массив TestAnswer с полями selectedOptionIds (для вопросов с выбором) и textAnswer (для открытых). Флаг requiresReview отмечает попытки с открытыми вопросами, требующими ручной проверки.'),
        emptyLine(),
        para('Звонки: CallSession хранит teacherId, studentId, уникальный inviteToken и livekitRoomName. Статус меняется по жизненному циклу: SCHEDULED → ACTIVE → ENDED. К сессии привязаны CallMessage (чат) и BoardDocument (состояние доски Excalidraw).'),
        emptyLine(),
        para('Живые уроки: Lesson связан с Course и может иметь связанный LessonUnit типа LIVE. При открытии такого урока студентом система ищет активный CallSession между ним и преподавателем и перенаправляет туда. К уроку привязаны Message (чат), Homework (задания) и LessonRoom (состояние доски).'),

        emptyLine(), emptyLine(),
        h2('2.2. Аутентификация и ролевая модель'),
        emptyLine(), emptyLine(),
        h3('2.2.1. Регистрация и вход'),
        emptyLine(),
        para('Аутентификация реализована без NextAuth.js — собственным решением на основе JWT. При регистрации (/api/auth/register) сервер проверяет уникальность email, хэширует пароль через bcrypt (cost factor 12) и создаёт запись User. При входе (/api/auth/login) сравнивается хэш, формируется JWT-токен с полями { id, name, email, role } и записывается в httpOnly-cookie с флагом Secure и SameSite=lax. Выход (/api/auth/logout) очищает cookie.'),
        emptyLine(),
        para('Функция requireUser() в lib/auth.ts читает и верифицирует JWT из cookie при каждом запросе к защищённым маршрутам. При истёкшем или отсутствующем токене выполняется redirect(\'/login\'). Функция rbac() в lib/rbac.ts проверяет соответствие роли требуемой — используется в Route Handlers для разграничения операций по ролям.'),
        emptyLine(), emptyLine(),
        h3('2.2.2. Роли пользователей'),
        emptyLine(),
        para('Система реализует три роли с иерархическим доступом.'),
        emptyLine(),
        tableCaption('Таблица 2.1'),
        tableTitle('Ролевая модель платформы SkillHub'),
        tableRoles(),
        emptyLine(),
        para('Роль фиксируется при регистрации. Администратор может изменить роль любого пользователя через прямое обновление базы данных (интерфейс панели администратора в текущей версии не реализован). Каждый Route Handler проверяет роль через rbac() и возвращает 403 Forbidden при несоответствии.'),

        emptyLine(), emptyLine(),
        h2('2.3. Курсы, модули и уроки'),
        emptyLine(), emptyLine(),
        h3('2.3.1. Структура курса'),
        emptyLine(),
        para('Преподаватель создаёт курс через форму CreateCourseForm (/api/courses POST), задавая название и описание. Курс по умолчанию находится в состоянии «черновик» и не виден студентам. Публикация выполняется вручную после наполнения контентом.'),
        emptyLine(),
        para('Внутри курса преподаватель создаёт модули (CourseModule) — тематические разделы — и добавляет к ним уроки (LessonUnit). Порядок модулей и уроков задаётся полем position. Перетаскивание элементов для изменения порядка реализовано в компоненте UnitEditor.'),
        emptyLine(), emptyLine(),
        h3('2.3.2. Типы уроков'),
        emptyLine(),
        para('Каждый урок имеет тип, определяющий его поведение при открытии студентом.'),
        emptyLine(),
        tableCaption('Таблица 2.2'),
        tableTitle('Типы уроков платформы (enum UnitType)'),
        tableUnitTypes(),
        emptyLine(),
        para('Тип LIVE — особый случай: при открытии такого урока маршрут /lesson/[id] ищет активный CallSession для пары «текущий студент + преподаватель курса» и перенаправляет на /calls/[id]. Если активного звонка нет, студент видит сообщение об ожидании.'),
        emptyLine(), emptyLine(),
        h3('2.3.3. Материалы и вложения'),
        emptyLine(),
        para('Материал урока хранится в модели LessonMaterial с полями content (Markdown-текст) и contentJson (структурированный JSON-контент) для уроков типа MATERIAL, а также videoUrl — ссылка на видеофайл для уроков типа VIDEO.'),
        emptyLine(),
        para('Вложения (UnitAttachment) — дополнительные файлы к уроку (PDF, изображения, архивы). Маршрут /api/units/[id]/attachments принимает файлы через FormData, сохраняет в /public/uploads и создаёт запись в базе. Поддерживаются два типа: FILE и IMAGE. Студент видит список вложений под контентом урока со ссылками для скачивания.'),
        emptyLine(), emptyLine(),
        h3('2.3.4. Отслеживание прогресса'),
        emptyLine(),
        para('При открытии урока студентом создаётся запись UnitProgress со статусом IN_PROGRESS. При нажатии кнопки «Завершить» маршрут /api/units/[id]/progress обновляет статус на COMPLETED и фиксирует completedAt. Поле progressPercent хранит промежуточный прогресс для видеоуроков.'),
        emptyLine(),
        para('Компонент CourseProgressBar вычисляет процент завершённых уроков из общего числа: запрашивает /api/courses/[id] и подсчитывает соотношение completed / total. Цветовая индикация: красный (0–33%), жёлтый (34–66%), синий (67–99%), зелёный (100%).'),
        emptyLine(),
        ...code([
          '// /api/units/[unitId]/progress route.ts',
          'await prisma.unitProgress.upsert({',
          '  where: { userId_unitId: { userId: user.id, unitId } },',
          '  create: { userId: user.id, unitId, courseId, status: "COMPLETED",',
          '            progressPercent: 100, completedAt: new Date() },',
          '  update: { status: "COMPLETED", progressPercent: 100,',
          '            completedAt: new Date() },',
          '});',
        ]),

        emptyLine(), emptyLine(),
        h2('2.4. Видеозвонки и живые уроки'),
        emptyLine(), emptyLine(),
        h3('2.4.1. Технология LiveKit'),
        emptyLine(),
        para('LiveKit — WebRTC-платформа с открытым исходным кодом. Сервер LiveKit управляет медиапотоками через протокол WebRTC (SRTP для шифрования медиа, DTLS для обмена ключами). Каждый участник комнаты идентифицируется JWT-токеном, подписанным API Key и Secret из переменных окружения LIVEKIT_API_KEY / LIVEKIT_API_SECRET.'),
        emptyLine(),
        para('Серверная генерация токена:'),
        emptyLine(),
        ...code([
          '// lib/livekit.ts',
          "import { AccessToken } from 'livekit-server-sdk';",
          '',
          'export async function generateLivekitToken(',
          '  roomName: string,',
          '  participantName: string,',
          '  participantId: string,',
          ') {',
          '  const token = new AccessToken(',
          '    process.env.LIVEKIT_API_KEY!,',
          '    process.env.LIVEKIT_API_SECRET!,',
          '    { identity: participantId, name: participantName },',
          '  );',
          '  token.addGrant({ room: roomName, roomJoin: true,',
          '                   canPublish: true, canSubscribe: true });',
          '  return {',
          '    token: await token.toJwt(),',
          '    wsUrl: process.env.LIVEKIT_WS_URL!,',
          '  };',
          '}',
        ]),
        emptyLine(),
        para('Клиентский компонент CallVideoRoom запрашивает токен с /api/calls/[id]/livekit-token, передаёт его в компонент Room из @livekit/components-react и отрисовывает видеопотоки всех участников (VideoTile). Параметры room: dynacast: true (автоматическое переключение качества) и adaptiveStream: true (подстройка под пропускную способность).'),
        emptyLine(), emptyLine(),
        h3('2.4.2. CallSession — звонок по ссылке'),
        emptyLine(),
        para('Преподаватель или администратор создаёт звонок через форму CreateCallForm на странице /calls. При создании генерируется уникальный inviteToken (cuid) и livekitRoomName. Студенту отправляется invite-ссылка вида /join/{token}.'),
        emptyLine(),
        para('Страница /join/[token] выполняет проверку: находит CallSession по токену, убеждается, что текущий пользователь является участником (teacherId или studentId), и перенаправляет на /calls/[id]. Посторонние получают сообщение «Нет доступа к этой ссылке».'),
        emptyLine(),
        para('Комната звонка (/calls/[id]) компонент CallRoom — трёхколонный макет:'),
        bullet('видеозона CallVideoRoom — LiveKit-видеопотоки участников с панелью управления (микрофон, камера);'),
        bullet('чат CallChat — текстовый обмен сообщениями в рамках текущей сессии;'),
        bullet('интерактивная доска ExcalidrawBoard — совместная доска ниже видео.'),
        emptyLine(), emptyLine(),
        h3('2.4.3. Живой урок (LIVE unit)'),
        emptyLine(),
        para('Живой урок — тип урока в структуре курса (unitType = LIVE), связанный с объектом Lesson. Страница /lesson/[id] отображает компонент LessonRoom, включающий LiveKitRoom, ExcalidrawBoard и LessonChat в едином интерфейсе. Дополнительно под комнатой отображается компонент HomeworkPanel с заданиями текущего урока.'),
        emptyLine(),
        para('Логика перенаправления: если студент открывает урок типа LIVE, сервер ищет последний CallSession для пары (teacherId курса, studentId). При наличии активного звонка студент перенаправляется на /calls/[id]. Если звонок ещё не создан, студент остаётся на странице живого урока и подключается к общей комнате.'),

        emptyLine(), emptyLine(),
        h2('2.5. Интерактивная доска Excalidraw'),
        emptyLine(), emptyLine(),
        h3('2.5.1. Синхронизация состояния доски'),
        emptyLine(),
        para('Компонент ExcalidrawBoard реализует простой механизм совместной работы через периодическое опрашивание (polling) REST API. Полное состояние доски сериализуется в JSON и хранится в PostgreSQL (поле boardState в LessonRoom или внутри CallSession через модель BoardDocument).'),
        emptyLine(),
        para('Алгоритм синхронизации:'),
        bullet('при монтировании компонент загружает начальное состояние с /api/calls/[id]/board или /api/lessons/[id]/board;'),
        bullet('при каждом изменении (onChange) запускается таймер дебаунса — если с момента последнего сохранения прошло более 2200 мс, состояние отправляется POST-запросом;'),
        bullet('отдельный интервал (3000 мс) опрашивает сервер на наличие изменений от других участников; проверяется поле updatedAt — если оно изменилось, состояние применяется через api.updateScene();'),
        bullet('защита от race condition: если delta между локальной записью и текущим временем < 2500 мс, polling-обновление пропускается.'),
        emptyLine(),
        para('Особенность реализации: поле collaborators в appState Excalidraw может принимать разные форматы (Map, Array, Object) в зависимости от версии библиотеки. Функция normalizeBoardState нормализует его к Map перед вызовом updateScene, предотвращая ошибки рендеринга.'),
        emptyLine(), emptyLine(),
        h3('2.5.2. Использование доски в звонках и уроках'),
        emptyLine(),
        para('Компонент ExcalidrawBoard принимает два взаимоисключающих пропса: callId (для звонка) или lessonId (для живого урока). В зависимости от переданного пропса формируется URL эндпоинта. Состояние доски персистентно между сессиями: если преподаватель нарисовал схему во время урока, студент увидит её при повторном входе.'),
        emptyLine(),
        para('Библиотека Excalidraw загружается через next/dynamic с { ssr: false } — это исключает серверный рендеринг, поскольку Excalidraw использует browser-only API. Ленивая загрузка сокращает начальный бандл страницы.'),

        emptyLine(), emptyLine(),
        h2('2.6. Чат в реальном времени'),
        emptyLine(),
        para('Платформа поддерживает два типа чата: чат живого урока (LessonChat) и чат звонка (CallChat). Оба компонента реализованы по одному принципу — polling каждые 2,5 секунды.'),
        emptyLine(),
        para('При отправке сообщения выполняется POST-запрос к /api/lessons/[id]/messages или /api/calls/[id]/messages. Сообщение сохраняется в модели Message (или CallMessage) и немедленно загружается через GET-запрос. Список сообщений обновляется автоматически у всех участников, открывших страницу.'),
        emptyLine(),
        para('Сообщения хранятся в базе данных и остаются доступными после завершения урока или звонка. Это позволяет студентам просмотреть историю обсуждения после занятия.'),
        emptyLine(),
        para('Технически polling уступает WebSocket по задержке (2,5 сек против < 100 мс), однако полностью совместим с serverless-деплоем на Vercel, где постоянные соединения не поддерживаются в Route Handlers. Для будущей оптимизации запланирована миграция на Server-Sent Events или LiveKit Data Channels.'),

        emptyLine(), emptyLine(),
        h2('2.7. Система тестирования'),
        emptyLine(), emptyLine(),
        h3('2.7.1. Типы вопросов'),
        emptyLine(),
        para('Система тестирования поддерживает три типа вопросов (enum TestQuestionType):'),
        bullet('SINGLE — одиночный выбор: студент выбирает один вариант из нескольких; автоматически проверяется сравнением selectedOptionIds с isCorrect-вариантами;'),
        bullet('MULTI — множественный выбор: студент может отметить несколько правильных ответов; начисляются баллы пропорционально верно отмеченным вариантам;'),
        bullet('OPEN — открытый ответ: студент вводит текст в поле textAnswer; флаг requiresReview устанавливается в true, попытка направляется на ручную проверку преподавателем.'),
        emptyLine(),
        para('Каждый вопрос имеет поле points — вес в итоговой оценке. Итоговый балл нормализуется от 0 до 100 по формуле: score / maxScore × 100.'),
        emptyLine(), emptyLine(),
        h3('2.7.2. Процесс прохождения теста'),
        emptyLine(),
        para('Тест открывается на странице /tests/[id]. Компонент TestRunner отображает вопросы последовательно. Студент выбирает ответы и нажимает «Отправить». POST /api/tests/[id]/attempts создаёт объект TestAttempt, сохраняет все TestAnswer и запускает автопроверку для вопросов типа SINGLE и MULTI.'),
        emptyLine(),
        para('При наличии вопросов OPEN попытка получает флаг requiresReview = true и отображается в панели аналитики преподавателя как «На проверке». Студент сразу видит результаты по автоматически проверяемым вопросам, а оценка за открытые вопросы появляется после проверки.'),
        emptyLine(),
        para('Студент может пересдать тест; каждая попытка сохраняется отдельно. В аналитике и в личном кабинете отображается лучшая попытка.'),
        emptyLine(), emptyLine(),
        h3('2.7.3. Проверка и оценивание'),
        emptyLine(),
        para('Страница /tests/[id]/review (компонент TestReviewClient) показывает детальный разбор последней попытки: по каждому вопросу выделяется данный ответ и правильный ответ, отображается итоговый процент. Преподаватель оценивает открытые вопросы через маршрут POST /api/attempts/[id]/grade, указывая score за каждый ответ.'),
        emptyLine(),
        para('Создание и редактирование тестов выполняется в компоненте TestsEditor: добавление/удаление вопросов, настройка вариантов ответа, публикация теста (isPublished).'),

        emptyLine(), emptyLine(),
        h2('2.8. Домашние задания'),
        emptyLine(), emptyLine(),
        h3('2.8.1. Создание и сдача задания'),
        emptyLine(),
        para('Преподаватель создаёт домашнее задание (Homework) в рамках урока (Lesson): указывает название, описание и необязательный дедлайн (dueDate). Задание видно студентам в компоненте HomeworkPanel на странице урока.'),
        emptyLine(),
        para('Студент сдаёт задание через POST /api/homework/[id]/submit, отправляя текстовый ответ в поле content. Допускается только одна сдача (@@unique([homeworkId, studentId])). Статус submission по умолчанию — «submitted».'),
        emptyLine(), emptyLine(),
        h3('2.8.2. Проверка преподавателем'),
        emptyLine(),
        para('Страница /homework/[id]/submissions отображает список всех сданных работ по заданию. Преподаватель видит имя студента, дату сдачи и содержимое ответа. Через компонент HomeworkGradeClient преподаватель выставляет числовую оценку (0–100) и текстовый комментарий.'),
        emptyLine(),
        para('PATCH /api/homework/submissions/[id] обновляет поля grade и comment в HomeworkSubmission и меняет статус на «graded». Студент видит оценку и комментарий в своём HomeworkPanel. Суммарная статистика по домашним заданиям отображается в модуле аналитики курса.'),

        emptyLine(), emptyLine(),
        h2('2.9. Аналитика успеваемости'),
        emptyLine(), emptyLine(),
        h3('2.9.1. Общая статистика курса'),
        emptyLine(),
        para('Страница /courses/[id]/stats доступна преподавателю и администратору. На ней отображаются три блока: сводная панель (hero), таблица по тестам и таблица по домашним заданиям, а также таблица студентов.'),
        emptyLine(),
        para('Сводная панель показывает четыре ключевых показателя: общее число записавшихся студентов; количество уроков в курсе; суммарное число попыток тестов; средний балл по всем тестам. Данные загружаются параллельным запросом Promise.all([enrollments, tests, homeworks, totalUnits, allUnitProgress]).'),
        emptyLine(),
        para('Таблица тестов по каждому тесту показывает:'),
        bullet('количество уникальных студентов, сдавших тест / общее число студентов;'),
        bullet('процент охвата (completionPct) в виде горизонтального прогресс-бара;'),
        bullet('средний балл с цветовой индикацией (зелёный ≥ 80%, жёлтый ≥ 50%, красный < 50%);'),
        bullet('количество попыток «На проверке» (открытые вопросы).'),
        emptyLine(),
        para('Таблица домашних заданий по каждому заданию показывает: количество сдавших, не сдавших, проверенных работ и среднюю оценку.'),
        emptyLine(), emptyLine(),
        h3('2.9.2. Детальная карточка студента'),
        emptyLine(),
        para('Страница /courses/[id]/stats/[studentId] отображает полную картину успеваемости конкретного студента по курсу: дату записи, процент выполненных уроков (прогресс-бар), статус по каждому тесту (сдал/не сдал, балл), статус по каждому домашнему заданию (сдал/не сдал, оценка, комментарий преподавателя).'),
        emptyLine(),
        para('Таблица StudentsTable на странице общей статистики является кликабельной — нажатие на строку студента открывает его детальную карточку через router.push(\'/courses/[id]/stats/[studentId]\').'),

        emptyLine(), emptyLine(),
        h2('2.10. Профиль пользователя и уведомления'),
        emptyLine(),
        para('Страница профиля /profile (компонент ProfileClient) предоставляет два блока. Блок «Личные данные»: форма изменения имени и пароля. При смене пароля требуется ввод текущего — сервер верифицирует его через bcrypt.compare. Email изменить нельзя. Блок «Информация об аккаунте»: отображение текущей роли и email (только для чтения).'),
        emptyLine(),
        para('Уведомления реализованы через компонент NotificationBell в шапке сайта. При загрузке компонент запрашивает GET /api/notifications и отображает числовой бейдж с количеством непрочитанных уведомлений. При клике открывается выпадающий список. Уведомления генерируются при ключевых событиях: проверке домашнего задания, оценке попытки теста с открытыми вопросами, приглашении на звонок.'),

        emptyLine(), emptyLine(),
        h2('2.11. API-интерфейс платформы'),
        emptyLine(),
        para('API построено на Next.js Route Handlers по принципам REST. Все маршруты защищены аутентификацией через requireUser(). Входные данные валидируются через zod-схемы. Ответы возвращаются в формате JSON. Список всех маршрутов приведён в табл. 2.3.'),
        emptyLine(),
        tableCaption('Таблица 2.3'),
        tableTitle('Полный список API-маршрутов платформы SkillHub'),
        tableApiMain(),
        emptyLine(),
        para('Загрузка файлов (/api/upload) принимает FormData, проверяет тип файла (image/*, application/pdf, .zip, .docx) и размер (максимум 10 МБ), сохраняет с UUID-именем в /public/uploads и возвращает публичный URL.'),

        emptyLine(), emptyLine(),
        h2('2.12. Деплой и мониторинг'),
        emptyLine(),
        para('Платформа развёртывается на Vercel — облачной платформе, созданной командой Next.js. Деплой полностью автоматизирован через интеграцию с GitHub: push в ветку main запускает сборку, TypeScript-проверку и атомарный деплой без простоя.'),
        emptyLine(),
        para('Оптимизации производительности, реализованные в проекте:'),
        bullet('Server Components: компоненты без интерактивности рендерятся на сервере, исключаются из клиентского бандла;'),
        bullet('next/dynamic с { ssr: false }: Excalidraw и LiveKit-компоненты загружаются лениво — начальный бандл уменьшается;'),
        bullet('next/image: автоконвертация изображений в WebP, lazy loading, генерация srcset;'),
        bullet('параллельные запросы к БД: Promise.all применяется везде, где данные независимы (страница аналитики делает 5 запросов параллельно);'),
        bullet('индексы PostgreSQL: составные индексы на UnitProgress ускоряют запросы аналитики.'),
        emptyLine(),
        para('Результаты Lighthouse-аудита для ключевых страниц приведены в табл. 2.4.'),
        emptyLine(),
        tableCaption('Таблица 2.4'),
        tableTitle('Результаты Lighthouse-аудита'),
        tableLighthouse(),
        emptyLine(),
        para('Переменные окружения: DATABASE_URL (PostgreSQL connection string), JWT_SECRET (подпись токенов), LIVEKIT_API_KEY, LIVEKIT_API_SECRET, LIVEKIT_WS_URL (LiveKit-сервер). На Vercel все переменные задаются в разделе Project Settings → Environment Variables.'),

        // ═══════════════════════════════════════════
        // ГЛАВА 3
        // ═══════════════════════════════════════════
        h1('3. ИНСТРУКЦИЯ ПОЛЬЗОВАТЕЛЯ'),

        emptyLine(),
        h2('3.1. Регистрация и вход'),
        emptyLine(),
        para('Главная страница (рис. 3.1) — маркетинговый лендинг с описанием возможностей платформы. Кнопка «Войти» в правом верхнем углу ведёт на страницу аутентификации.'),
        emptyLine(),
        figCaption('3.1', 'Главная страница платформы SkillHub'),
        emptyLine(),
        para('Страница входа (рис. 3.2): поля email и пароль, кнопка «Войти». Ссылка «Ещё нет аккаунта?» ведёт на форму регистрации (рис. 3.3), где необходимо заполнить Имя, Email, Пароль и Подтверждение пароля. После регистрации пользователь получает роль STUDENT и перенаправляется в личный кабинет.'),
        emptyLine(),
        figCaption('3.2', 'Страница входа'),
        emptyLine(),
        figCaption('3.3', 'Страница регистрации'),

        emptyLine(), emptyLine(),
        h2('3.2. Режим студента'),
        emptyLine(),
        para('После входа студент попадает на страницу /dashboard (рис. 3.4) — личный кабинет с прогрессом по записанным курсам. В шапке доступна навигация: «Каталог курсов», иконка уведомлений, кнопка «Профиль».'),
        emptyLine(),
        figCaption('3.4', 'Личный кабинет студента'),
        emptyLine(),
        para('Каталог курсов (/courses, рис. 3.5) отображает карточки опубликованных курсов. Нажатие на карточку открывает страницу курса (рис. 3.6) с описанием, деревом модулей и уроков, кнопкой записи. После записи курс появляется в личном кабинете.'),
        emptyLine(),
        figCaption('3.5', 'Каталог курсов'),
        emptyLine(),
        figCaption('3.6', 'Страница курса'),
        emptyLine(),
        para('Для прохождения урока студент нажимает на его название в дереве курса и попадает на страницу /learn/[unitId] (рис. 3.7). Страница отображает материал согласно типу урока: текст/видео для MATERIAL и VIDEO, форму с вопросами для TEST. Кнопка «Завершить урок» фиксирует прогресс.'),
        emptyLine(),
        figCaption('3.7', 'Страница прохождения урока'),
        emptyLine(),
        para('При наличии вложений к уроку под основным контентом отображается секция «Материалы» со списком файлов для скачивания.'),
        emptyLine(),
        para('Если урок имеет тип LIVE, студент перенаправляется на звонок с преподавателем (см. раздел 3.4). Для прохождения теста студент открывает соответствующий урок типа TEST, отвечает на вопросы и нажимает «Отправить». Результаты сразу отображаются на странице разбора (/tests/[id]/review, рис. 3.8).'),
        emptyLine(),
        figCaption('3.8', 'Разбор результатов теста'),
        emptyLine(),
        para('Домашнее задание отображается в HomeworkPanel на странице урока. Студент вводит ответ в текстовое поле и нажимает «Сдать». После проверки преподавателем в этом же поле появляется оценка и комментарий.'),
        emptyLine(),
        para('Профиль (/profile, рис. 3.9): изменение имени, смена пароля. Email изменить нельзя.'),
        emptyLine(),
        figCaption('3.9', 'Профиль пользователя'),

        emptyLine(), emptyLine(),
        h2('3.3. Режим преподавателя'),
        emptyLine(),
        para('Пользователь с ролью TEACHER имеет доступ к функциям создания контента. В каталоге курсов доступна кнопка «Создать курс» (рис. 3.10). После создания курс открывается в редакторе.'),
        emptyLine(),
        figCaption('3.10', 'Создание курса'),
        emptyLine(),
        para('Редактор курса (рис. 3.11) — страница /courses/[id]. В левой панели дерево модулей и уроков с кнопками добавления. Нажатие на урок открывает редактор материала (рис. 3.12), где можно загрузить текстовый контент в формате Markdown или ссылку на видео, прикрепить файлы-вложения, создать тест.'),
        emptyLine(),
        figCaption('3.11', 'Редактор структуры курса'),
        emptyLine(),
        figCaption('3.12', 'Редактор материала урока'),
        emptyLine(),
        para('Для создания теста преподаватель переходит в компонент TestsEditor, добавляет вопросы с вариантами ответа и публикует тест. Домашнее задание создаётся через кнопку «Добавить задание» на странице живого урока.'),
        emptyLine(),
        para('Страница статистики курса (/courses/[id]/stats, рис. 3.13) доступна через кнопку «Аналитика» на странице курса. Преподаватель видит сводные показатели, таблицу по тестам и домашним заданиям, а также список студентов с их прогрессом. Нажатие на студента открывает его детальную карточку.'),
        emptyLine(),
        figCaption('3.13', 'Страница аналитики курса'),
        emptyLine(),
        para('Домашние задания на проверку: страница /homework/[id]/submissions — список сданных работ. Преподаватель открывает работу, читает ответ студента и выставляет оценку с комментарием.'),

        emptyLine(), emptyLine(),
        h2('3.4. Видеозвонок'),
        emptyLine(),
        para('Для проведения индивидуального урока преподаватель переходит на страницу «Звонки» (/calls, рис. 3.14), нажимает «Новый звонок», выбирает студента из списка, вводит тему и дату. После создания система генерирует invite-ссылку вида /join/{token}.'),
        emptyLine(),
        figCaption('3.14', 'Страница управления звонками'),
        emptyLine(),
        para('Студент переходит по invite-ссылке (или открывает урок типа LIVE) и попадает на страницу /calls/[id] (рис. 3.15). Страница содержит три элемента: видеозону с панелью управления (микрофон, камера), чат для текстового общения и интерактивную доску Excalidraw ниже.'),
        emptyLine(),
        figCaption('3.15', 'Комната видеозвонка'),
        emptyLine(),
        para('На доске (рис. 3.16) участники могут рисовать, писать текст, добавлять фигуры и изображения. Все изменения синхронизируются между участниками через опрос сервера каждые 3 секунды и сохраняются в базе данных.'),
        emptyLine(),
        figCaption('3.16', 'Интерактивная доска Excalidraw'),

        // ═══════════════════════════════════════════
        // ЗАКЛЮЧЕНИЕ
        // ═══════════════════════════════════════════
        h1('ЗАКЛЮЧЕНИЕ'),
        emptyLine(),
        para('В рамках настоящего проекта спроектирована и реализована образовательная платформа SkillHub — полнофункциональный прототип системы онлайн-обучения, охватывающий полный образовательный цикл: от создания курса преподавателем до аналитики успеваемости каждого студента.'),
        emptyLine(),
        para('Достигнутые технические результаты.'),
        emptyLine(),
        para('1. Архитектура. Next.js 14 App Router с React Server Components обеспечивает гибридный рендеринг: статические страницы (лендинг, каталог) генерируются на этапе сборки, персонализированные страницы используют серверные компоненты с прямым доступом к БД, интерактивные элементы — клиентские компоненты. Feature-Sliced Design обеспечивает чёткое разделение ответственности и упрощает навигацию по коду.'),
        emptyLine(),
        para('2. Безопасность. Многоуровневая защита: JWT в httpOnly-cookie, Middleware-перехват неаутентифицированных запросов, ролевая модель STUDENT/TEACHER/ADMIN с проверкой в каждом Route Handler, bcrypt-хэширование паролей, zod-валидация всех входных данных, ограничение типов и размеров загружаемых файлов.'),
        emptyLine(),
        para('3. Real-time функции. Видеоконференции на базе LiveKit WebRTC обеспечивают качественную связь с адаптивным битрейтом (dynacast). Совместная доска Excalidraw синхронизируется через REST-polling с персистентным хранением в PostgreSQL. Чат реализован polling-механизмом, совместимым с Vercel serverless.'),
        emptyLine(),
        para('4. База данных. Схема Prisma + PostgreSQL с 17 моделями охватывает все сущности платформы. Составные уникальные индексы гарантируют целостность данных (один прогресс на пару пользователь+урок, одна сдача ДЗ). Индексы на часто используемых полях ускоряют запросы аналитики.'),
        emptyLine(),
        para('5. Аналитика. Страница статистики курса агрегирует данные о 5 типах сущностей в одном запросе (Promise.all), вычисляет метрики охвата, средние баллы и статусы домашних заданий. Детальная карточка студента даёт преподавателю полную картину успеваемости в разрезе каждого задания.'),
        emptyLine(),
        para('6. Производительность. Lighthouse Performance Score: 84–97 баллов в зависимости от страницы. FCP (First Contentful Paint): 0,8–1,2 секунды.'),
        emptyLine(),
        para('Полностью реализованный функционал платформы:'),
        bullet('трёхуровневая ролевая модель (ADMIN / TEACHER / STUDENT);'),
        bullet('создание и управление курсами с иерархией модулей и уроков;'),
        bullet('четыре типа уроков: текстовые материалы, видео, тесты, живые уроки;'),
        bullet('вложения к урокам (файлы и изображения);'),
        bullet('отслеживание прогресса студента с детальной историей;'),
        bullet('система тестирования: три типа вопросов, автопроверка + ручная;'),
        bullet('домашние задания с дедлайном, сдачей и проверкой;'),
        bullet('видеозвонки на базе LiveKit с invite-ссылками;'),
        bullet('живые уроки с видео, Excalidraw-доской и чатом;'),
        bullet('совместная интерактивная доска с персистентностью;'),
        bullet('аналитика успеваемости на уровне курса и отдельного студента;'),
        bullet('уведомления о ключевых событиях;'),
        bullet('профиль с изменением имени и пароля;'),
        bullet('загрузка файлов с валидацией типа и размера.'),
        emptyLine(),
        para('Направления дальнейшего развития:'),
        bullet('WebSocket или Server-Sent Events для чата вместо polling;'),
        bullet('LiveKit Data Channels для низкозадержечной синхронизации доски;'),
        bullet('запись видеоуроков (LiveKit Egress);'),
        bullet('мобильное приложение на React Native;'),
        bullet('платёжная интеграция (ЮKassa / Stripe) для монетизации курсов;'),
        bullet('расширенная аналитика: воронка прохождения, когортный анализ, экспорт в Excel.'),

        // ═══════════════════════════════════════════
        // ПРИЛОЖЕНИЕ
        // ═══════════════════════════════════════════
        h1('ПРИЛОЖЕНИЕ'),
        emptyLine(),
        paraNoIndent('Листинг А.1 — Компонент ExcalidrawBoard.tsx (сокращённо)', true),
        emptyLine(),
        ...code([
          '"use client";',
          'import dynamic from "next/dynamic";',
          '',
          'const Excalidraw = dynamic(',
          '  async () => (await import("@excalidraw/excalidraw")).Excalidraw,',
          '  { ssr: false },',
          ');',
          '',
          'export function ExcalidrawBoard({ lessonId, callId }) {',
          '  const boardEndpoint = callId',
          '    ? `/api/calls/${callId}/board`',
          '    : `/api/lessons/${lessonId}/board`;',
          '',
          '  // Polling каждые 3 сек для синхронизации между участниками',
          '  useEffect(() => {',
          '    const interval = setInterval(async () => {',
          '      if (Date.now() - lastLocalWriteAtRef.current < 2500) return;',
          '      const res = await fetch(boardEndpoint, { cache: "no-store" });',
          '      const data = await res.json();',
          '      if (data.updatedAt !== lastSyncAtRef.current) {',
          '        apiRef.current?.updateScene(',
          '          normalizeBoardState(data.boardState)',
          '        );',
          '        lastSyncAtRef.current = data.updatedAt;',
          '      }',
          '    }, 3000);',
          '    return () => clearInterval(interval);',
          '  }, [boardEndpoint, ready]);',
          '',
          '  return (',
          '    <Excalidraw',
          '      initialData={initialData}',
          '      excalidrawAPI={(api) => { apiRef.current = api; }}',
          '      onChange={(elements, appState, files) => {',
          '        // Дебаунс 2200 мс перед отправкой',
          '        if (Date.now() - lastSavedAtRef.current < 2200) return;',
          '        fetch(boardEndpoint, {',
          '          method: "POST",',
          '          body: JSON.stringify({ boardState: { elements, appState, files } })',
          '        });',
          '      }}',
          '    />',
          '  );',
          '}',
        ]),
        emptyLine(),
        paraNoIndent('Листинг А.2 — Генерация LiveKit-токена (lib/livekit.ts)', true),
        emptyLine(),
        ...code([
          "import { AccessToken } from 'livekit-server-sdk';",
          '',
          'export async function generateLivekitToken(',
          '  roomName: string,',
          '  participantName: string,',
          '  participantId: string,',
          ') {',
          '  const at = new AccessToken(',
          '    process.env.LIVEKIT_API_KEY!,',
          '    process.env.LIVEKIT_API_SECRET!,',
          '    { identity: participantId, name: participantName },',
          '  );',
          '  at.addGrant({',
          '    room: roomName, roomJoin: true,',
          '    canPublish: true, canSubscribe: true,',
          '  });',
          '  return { token: await at.toJwt(),',
          '           wsUrl: process.env.LIVEKIT_WS_URL! };',
          '}',
        ]),
        emptyLine(),
        paraNoIndent('Листинг А.3 — Фрагмент схемы Prisma: CallSession и BoardDocument', true),
        emptyLine(),
        ...code([
          'enum CallStatus { SCHEDULED  ACTIVE  ENDED  CANCELLED }',
          '',
          'model CallSession {',
          '  id              String     @id @default(cuid())',
          '  teacherId       String',
          '  studentId       String',
          '  inviteToken     String     @unique',
          '  status          CallStatus @default(SCHEDULED)',
          '  topic           String?',
          '  scheduledAt     DateTime?',
          '  livekitRoomName String     @unique',
          '  createdAt       DateTime   @default(now())',
          '  teacher         User       @relation("CallTeacher", ...)',
          '  student         User       @relation("CallStudent", ...)',
          '  messages        CallMessage[]',
          '}',
          '',
          'model BoardDocument {',
          '  id         String @id @default(cuid())',
          '  teacherId  String',
          '  studentId  String',
          '  boardState Json?',
          '  updatedAt  DateTime @updatedAt',
          '  @@unique([teacherId, studentId])',
          '}',
        ]),
        emptyLine(),
        paraNoIndent('Листинг А.4 — Страница аналитики курса: параллельная загрузка данных', true),
        emptyLine(),
        ...code([
          'const [enrollments, tests, homeworks, totalUnits, allUnitProgress]',
          '  = await Promise.all([',
          '    prisma.enrollment.findMany({',
          '      where: { courseId: id },',
          '      include: { user: { select: { id, name, email } } }',
          '    }),',
          '    prisma.test.findMany({',
          '      where: { courseId: id, isPublished: true },',
          '      include: { attempts: { where: { submittedAt: { not: null } } } }',
          '    }),',
          '    prisma.homework.findMany({',
          '      where: { courseId: id },',
          '      include: { submissions: { select: { studentId, grade } } }',
          '    }),',
          '    prisma.lessonUnit.count({',
          '      where: { module: { courseId: id } }',
          '    }),',
          '    prisma.unitProgress.findMany({',
          '      where: { courseId: id },',
          '      select: { userId, unitId, status }',
          '    }),',
          '  ]);',
        ]),
      ],
    },
  ],
});

const buffer = await Packer.toBuffer(doc);
const fname = 'Отчет_SkillHub_v4_полный.docx';
writeFileSync(fname, buffer);
console.log(`Done: ${fname}`);
