import {
  Document, Packer, Paragraph, TextRun, AlignmentType,
  PageBreak, convertInchesToTwip, LevelFormat,
  TabStopType, TabStopPosition, UnderlineType, BorderStyle,
  Table, TableRow, TableCell, WidthType, ShadingType,
} from "docx";
import { writeFileSync } from "fs";

const FONT = "Times New Roman";
const SIZE_BODY = 28;
const SIZE_HEADING1 = 28;
const SIZE_HEADING2 = 28;
const SIZE_TITLE = 32;

function body(text, opts = {}) {
  return new Paragraph({
    alignment: opts.align ?? AlignmentType.JUSTIFIED,
    spacing: { line: 360, before: 0, after: 0 },
    indent: opts.noIndent ? {} : { firstLine: convertInchesToTwip(0.5) },
    children: [
      new TextRun({
        text,
        font: FONT,
        size: SIZE_BODY,
        bold: opts.bold ?? false,
        italics: opts.italic ?? false,
        underline: opts.underline ? { type: UnderlineType.SINGLE } : undefined,
      }),
    ],
  });
}

function empty() {
  return new Paragraph({ children: [new TextRun({ text: "", font: FONT, size: SIZE_BODY })] });
}

function heading1(text, num) {
  return new Paragraph({
    alignment: AlignmentType.LEFT,
    spacing: { line: 360, before: 200, after: 200 },
    children: [new TextRun({ text: `${num}. ${text}`, font: FONT, size: SIZE_HEADING1, bold: true })],
  });
}

function heading2(text, num) {
  return new Paragraph({
    alignment: AlignmentType.LEFT,
    spacing: { line: 360, before: 160, after: 120 },
    children: [new TextRun({ text: `${num} ${text}`, font: FONT, size: SIZE_HEADING2, bold: true })],
  });
}

function heading3(text, num) {
  return new Paragraph({
    alignment: AlignmentType.LEFT,
    spacing: { line: 360, before: 120, after: 80 },
    indent: { firstLine: convertInchesToTwip(0.5) },
    children: [new TextRun({ text: `${num} ${text}`, font: FONT, size: SIZE_BODY, bold: true })],
  });
}

function centered(text, opts = {}) {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { line: 360, before: opts.before ?? 0, after: opts.after ?? 0 },
    children: [
      new TextRun({
        text,
        font: FONT,
        size: opts.size ?? SIZE_BODY,
        bold: opts.bold ?? false,
        underline: opts.underline ? { type: UnderlineType.SINGLE } : undefined,
      }),
    ],
  });
}

function bullet(text) {
  return new Paragraph({
    alignment: AlignmentType.JUSTIFIED,
    spacing: { line: 360 },
    indent: { left: convertInchesToTwip(0.5), hanging: convertInchesToTwip(0.25) },
    bullet: { level: 0 },
    children: [new TextRun({ text, font: FONT, size: SIZE_BODY })],
  });
}

function caption(text) {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { line: 300, before: 80, after: 80 },
    children: [new TextRun({ text, font: FONT, size: 24, italics: true })],
  });
}

function pageBreak() {
  return new Paragraph({ children: [new PageBreak()] });
}

function tocLine(title, page) {
  return new Paragraph({
    alignment: AlignmentType.LEFT,
    spacing: { line: 300 },
    tabStops: [{ type: TabStopType.RIGHT, position: 9000, leader: "dot" }],
    children: [
      new TextRun({ text: title, font: FONT, size: SIZE_BODY }),
      new TextRun({ text: "\t", font: FONT, size: SIZE_BODY }),
      new TextRun({ text: page, font: FONT, size: SIZE_BODY }),
    ],
  });
}

function codeBlock(lines) {
  return new Paragraph({
    shading: { type: ShadingType.SOLID, color: "F2F2F2" },
    border: {
      top: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
      left: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
      right: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
    },
    spacing: { line: 240, before: 80, after: 80 },
    indent: { left: convertInchesToTwip(0.2), right: convertInchesToTwip(0.2) },
    children: lines.flatMap((line, i) => [
      new TextRun({ text: line, font: "Courier New", size: 20, break: i > 0 ? 1 : 0 }),
    ]),
  });
}

function makeTable(headers, rows) {
  const headerRow = new TableRow({
    tableHeader: true,
    children: headers.map(h =>
      new TableCell({
        shading: { type: ShadingType.SOLID, color: "D9D9D9" },
        children: [new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: h, font: FONT, size: 22, bold: true })],
        })],
      })
    ),
  });
  const dataRows = rows.map(row =>
    new TableRow({
      children: row.map((cell, i) =>
        new TableCell({
          children: [new Paragraph({
            alignment: i === 0 ? AlignmentType.LEFT : AlignmentType.CENTER,
            children: [new TextRun({ text: cell, font: FONT, size: 22 })],
          })],
        })
      ),
    })
  );
  return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [headerRow, ...dataRows] });
}

// ──────────────────────────────────────────────
// DOCUMENT
// ──────────────────────────────────────────────
const doc = new Document({
  numbering: {
    config: [{
      reference: "bullet-list",
      levels: [{
        level: 0,
        format: LevelFormat.BULLET,
        text: "–",
        alignment: AlignmentType.LEFT,
        style: {
          paragraph: { indent: { left: convertInchesToTwip(0.5), hanging: convertInchesToTwip(0.25) } },
        },
      }],
    }],
  },
  sections: [{
    properties: {
      page: {
        margin: {
          top: convertInchesToTwip(1.18),
          bottom: convertInchesToTwip(0.98),
          left: convertInchesToTwip(1.18),
          right: convertInchesToTwip(0.59),
        },
      },
    },
    children: [

      // ── ТИТУЛЬНЫЙ ЛИСТ ──────────────────────────
      centered("МИНИСТЕРСТВО ЦИФРОВОГО РАЗВИТИЯ, СВЯЗИ И", { size: SIZE_BODY }),
      centered("МАССОВЫХ КОММУНИКАЦИЙ РОССИЙСКОЙ ФЕДЕРАЦИИ", { size: SIZE_BODY }),
      empty(),
      centered("ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБРАЗОВАТЕЛЬНОЕ", { size: SIZE_BODY }),
      centered("УЧРЕЖДЕНИЕ ВЫСШЕГО ОБРАЗОВАНИЯ", { size: SIZE_BODY }),
      empty(),
      centered("«САНКТ-ПЕТЕРБУРГСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ", { size: SIZE_BODY, bold: true }),
      centered("ТЕЛЕКОММУНИКАЦИЙ ИМ. ПРОФ. М. А. БОНЧ-БРУЕВИЧА»", { size: SIZE_BODY, bold: true }),
      empty(),
      centered("(СПбГУТ)", { size: SIZE_BODY, bold: true }),
      empty(),
      empty(),
      centered("ПРОЕКТ", { size: SIZE_TITLE, bold: true, before: 400 }),
      empty(),
      centered("«Разработка платформы для онлайн-обучения на базе веб-технологий»", {
        size: SIZE_TITLE, bold: true, after: 400,
      }),
      empty(),
      empty(),
      empty(),
      empty(),
      new Paragraph({
        alignment: AlignmentType.LEFT,
        spacing: { line: 360 },
        tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
        children: [
          new TextRun({ text: "Руководитель, старший преподаватель", font: FONT, size: SIZE_BODY }),
          new TextRun({ text: "\t", font: FONT, size: SIZE_BODY }),
          new TextRun({ text: "Дагаев А.В.", font: FONT, size: SIZE_BODY }),
        ],
      }),
      new Paragraph({
        alignment: AlignmentType.LEFT,
        spacing: { line: 360 },
        tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
        children: [new TextRun({ text: "подпись, дата", font: FONT, size: SIZE_BODY, italics: true })],
      }),
      empty(),
      empty(),
      new Paragraph({
        alignment: AlignmentType.LEFT,
        spacing: { line: 360 },
        tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
        children: [
          new TextRun({ text: "Исполнитель, группа ИКПИ-31", font: FONT, size: SIZE_BODY }),
          new TextRun({ text: "\t", font: FONT, size: SIZE_BODY }),
          new TextRun({ text: "Кибалин О.И.", font: FONT, size: SIZE_BODY }),
        ],
      }),
      new Paragraph({
        alignment: AlignmentType.LEFT,
        spacing: { line: 360 },
        tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
        children: [new TextRun({ text: "подпись, дата", font: FONT, size: SIZE_BODY, italics: true })],
      }),
      empty(),
      empty(),
      empty(),
      empty(),
      centered("Санкт-Петербург", { size: SIZE_BODY }),
      centered("2025", { size: SIZE_BODY }),

      // ── ОГЛАВЛЕНИЕ ─────────────────────────────
      pageBreak(),
      centered("ОГЛАВЛЕНИЕ", { size: SIZE_BODY, bold: true, underline: true }),
      empty(),
      tocLine("ВВЕДЕНИЕ", "3"),
      tocLine("1. Описание технологий", "5"),
      tocLine("   1.1 Сравнение технологий разработки веб-приложений", "5"),
      tocLine("   1.2 Описание используемых технологий", "9"),
      tocLine("   1.3 Применяемые подходы к обучению", "13"),
      tocLine("2. Разработка платформы для онлайн-обучения", "17"),
      tocLine("   2.1 Архитектура приложения и модели данных", "17"),
      tocLine("   2.2 База данных и серверная логика (API Routes)", "23"),
      tocLine("   2.3 Реализация функционала курсов и уроков", "27"),
      tocLine("   2.4 Система прогресса и статистики", "31"),
      tocLine("   2.5 Видеозвонки, совместная доска и домашние задания", "35"),
      tocLine("   2.6 Деплой и инфраструктура", "39"),
      tocLine("3. Инструкция пользователя", "42"),
      tocLine("ЗАКЛЮЧЕНИЕ", "54"),
      tocLine("ПРИЛОЖЕНИЕ", "56"),

      // ── ВВЕДЕНИЕ ──────────────────────────────
      pageBreak(),
      centered("ВВЕДЕНИЕ", { size: SIZE_BODY, bold: true, underline: true }),
      empty(),
      body("Современное образование переживает глубокую цифровую трансформацию. Пандемия COVID-19 ускорила этот процесс: тысячи учебных заведений были вынуждены перейти в дистанционный формат, обнажив слабые стороны существующих платформ — перегруженный интерфейс, медленную загрузку, отсутствие гибкости настройки и невозможность полноценно отслеживать прогресс каждого студента в реальном времени. Рынок образовательных технологий (EdTech) в России продолжает активно расти: по данным аналитических агентств, объём российского рынка онлайн-образования превысил 100 млрд рублей в 2024 году."),
      empty(),
      body("Ключевые проблемы существующих решений, таких как Moodle, Stepik и Coursera, можно разделить на три группы. Во-первых, техническая: эти платформы используют устаревшие архитектурные подходы, что приводит к медленной загрузке страниц и высокой нагрузке на серверы при одновременном присутствии большого числа пользователей. Во-вторых, функциональная: большинство платформ предлагают либо избыточный функционал, перегружающий интерфейс, либо не позволяют преподавателям гибко настраивать курсы под конкретные учебные задачи. В-третьих, аналитическая: инструменты отслеживания прогресса студентов зачастую упрощены до базовых метрик, не позволяя преподавателю получить детальную картину успеваемости."),
      empty(),
      body("Настоящий проект направлен на разработку полнофункциональной платформы для онлайн-обучения «SkillHub», ориентированной на учебные заведения и частных преподавателей. Платформа решает выявленные проблемы за счёт следующих ключевых возможностей:"),
      bullet("Многоролевая система доступа (студент, преподаватель, администратор) с чётким разграничением прав."),
      bullet("Гибкий редактор курсов с поддержкой иерархии «курс → модуль → занятие», Markdown-текста, встроенных изображений, прикреплённых файлов, видео, тестов и домашних заданий."),
      bullet("Двухуровневая система прогресса: мгновенное локальное обновление через localStorage и надёжная персистентность в PostgreSQL."),
      bullet("Тесты с тремя типами вопросов (одиночный выбор, множественный выбор, открытый ответ) и немедленной обратной связью по итогам попытки."),
      bullet("Видеозанятия в реальном времени на базе LiveKit WebRTC с системой приглашений по уникальному токену."),
      bullet("Совместная интерактивная доска (whiteboard) для преподавателя и студента в рамках видеосессии."),
      bullet("Детальная аналитика для преподавателя: прогресс каждого студента по занятиям, разбор тестов с цветовой подсветкой ответов, история домашних заданий."),
      bullet("Система уведомлений и личный кабинет с настройками профиля."),
      empty(),
      body("Для реализации выбран стек современных веб-технологий: Next.js 16 (App Router) в связке с TypeScript обеспечивает типобезопасный серверный рендеринг и удобную маршрутизацию; Prisma ORM — строго типизированный доступ к базе данных PostgreSQL (облачный хостинг Neon); Tailwind CSS — быструю стилизацию без отдельных CSS-файлов; NextAuth.js — безопасную аутентификацию на основе JWT-токенов; LiveKit — масштабируемые WebRTC-видеозвонки с открытым исходным кодом."),
      empty(),
      body("Результатом проекта является работающее веб-приложение с задокументированным API из более чем 40 Route Handler-ов, охватывающих аутентификацию, управление курсами, прогрессом, тестами, домашними заданиями, видеозвонками и загрузкой файлов. Платформа задеплоена на облачной инфраструктуре Vercel и готова к использованию в учебном процессе."),
      empty(),
      body("Структура отчёта: в первом разделе рассмотрены технологические альтернативы и обоснован выбор стека; во втором — детально описана реализация всех компонентов платформы; в третьем — приведена инструкция пользователя для каждой роли."),

      // ── ГЛАВА 1 ────────────────────────────────
      pageBreak(),
      heading1("Описание технологий", "1"),
      empty(),
      heading2("Сравнение технологий разработки веб-приложений", "1.1"),
      empty(),
      body("Выбор технологического стека для образовательной платформы определяется рядом требований: высокая производительность при рендеринге страниц с большим объёмом контента, надёжная типизация для снижения числа ошибок в крупной кодовой базе, простота деплоя и поддержки, наличие зрелой экосистемы."),
      empty(),
      body("Фронтенд-фреймворки", { bold: true, noIndent: true }),
      empty(),
      body("React — наиболее распространённая библиотека для построения пользовательских интерфейсов. Её компонентная модель, виртуальный DOM и огромная экосистема (более 4 млн пакетов npm) делают её стандартом де-факто для сложных веб-приложений. Однако React сам по себе является лишь библиотекой для UI: маршрутизацию, серверный рендеринг и оптимизацию сборки необходимо настраивать отдельно."),
      empty(),
      body("Next.js, построенный поверх React, устраняет эту проблему, предоставляя «из коробки» серверный рендеринг (SSR), статическую генерацию (SSG), файловую маршрутизацию, встроенный API-слой и оптимизацию изображений. Начиная с версии 13, Next.js App Router вводит концепцию серверных компонентов React (RSC), которые рендерятся исключительно на сервере и могут напрямую обращаться к базе данных — без промежуточного API. Это принципиально снижает количество клиентских JS-запросов и ускоряет первичную загрузку."),
      empty(),
      body("Vue.js предлагает более пологую кривую обучения и встроенную реактивность на основе Proxy, что делает его привлекательным для небольших команд. Однако его экосистема уступает React по объёму, а поддержка TypeScript, несмотря на значительное улучшение в Vue 3, всё ещё менее зрелая. Vue практически не представлен в крупных корпоративных проектах по сравнению с React и Angular."),
      empty(),
      body("Angular — полноценный фреймворк с dependency injection, декораторами, встроенной поддержкой TypeScript и жёсткой архитектурой (модули, сервисы, компоненты). Он идеально подходит для масштабных enterprise-приложений с большими командами и строгими корпоративными стандартами. Для образовательной платформы средней сложности его избыточность увеличивает порог входа без ощутимых выгод."),
      empty(),
      body("Серверные технологии", { bold: true, noIndent: true }),
      empty(),
      body("Классический подход предполагает разделение фронтенда (SPA на React/Vue) и бэкенда (REST-сервер на Express, FastAPI или Django REST Framework). Это усложняет деплой (два отдельных сервиса), создаёт необходимость синхронизировать типы данных между клиентом и сервером, а также добавляет задержку на каждый API-запрос."),
      empty(),
      body("Next.js App Router решает эту проблему элегантно: серверные компоненты обращаются к базе данных напрямую, а Route Handlers (файлы route.ts) реализуют REST-эндпоинты в рамках того же проекта. Типы Prisma автоматически доступны как на «серверной», так и на «клиентской» стороне одного монорепозитория, что исключает дрейф типов."),
      empty(),
      body("ORM и базы данных", { bold: true, noIndent: true }),
      empty(),
      body("PostgreSQL является промышленным стандартом для реляционных баз данных: ACID-транзакции, полнотекстовый поиск, поддержка JSONB-полей, индексы, внешние ключи. Для образовательной платформы с множеством связанных сущностей (пользователи, курсы, прогресс, тесты) реляционная модель значительно удобнее NoSQL."),
      empty(),
      body("Prisma ORM — современный TypeScript-first инструмент: декларативная схема в файле schema.prisma компилируется в типизированный клиент PrismaClient, что обеспечивает автодополнение и проверку типов при написании запросов. Альтернатива TypeORM страдает от сложного синтаксиса и устаревших паттернов. Drizzle ORM — более новый инструмент с меньшим объёмом документации и сообщества."),
      empty(),
      caption("Таблица 1 – Сравнение основных технологических решений"),
      makeTable(
        ["Параметр", "Next.js + Prisma", "React + Express", "Vue + Django DRF", "Angular + NestJS"],
        [
          ["Типобезопасность", "TypeScript end-to-end", "Частичная", "Python typing", "TypeScript"],
          ["Рендеринг", "SSR + SSG + RSC", "CSR (SPA)", "SSR (Nuxt)", "SSR (Universal)"],
          ["ORM", "Prisma (типизированный)", "TypeORM / Sequelize", "Django ORM", "TypeORM"],
          ["Деплой", "Vercel (автоматический)", "Отдельный сервер", "2 сервиса", "2 сервиса"],
          ["Единая кодовая база", "Да", "Нет", "Нет", "Нет"],
          ["Порог входа", "Средний", "Низкий–средний", "Низкий–средний", "Высокий"],
          ["Зрелость экосистемы", "Очень высокая", "Высокая", "Средняя", "Высокая"],
        ]
      ),
      empty(),
      body("На основании проведённого анализа для реализации SkillHub был выбран стек Next.js 16 + TypeScript + Prisma + PostgreSQL (Neon). Такое решение обеспечивает единую кодовую базу, сквозную типизацию, минимальный деплой и высокую производительность за счёт серверных компонентов React."),
      empty(),

      heading2("Описание используемых технологий", "1.2"),
      empty(),
      body("Next.js 16 (App Router)", { bold: true, noIndent: true }),
      empty(),
      body("Next.js — это фреймворк для React-приложений производства компании Vercel. Версия 16 с App Router вводит принципиально новую модель компонентов. Серверные компоненты (Server Components) рендерятся на сервере при каждом запросе или во время сборки, имеют прямой доступ к базе данных и не включают JavaScript в клиентский бандл. Клиентские компоненты (Client Components) добавляют директиву «use client» и получают возможность использовать хуки React (useState, useEffect) и обработчики событий."),
      empty(),
      body("В проекте SkillHub серверные компоненты используются для страниц курсов, дашборда и статистики — они загружают данные через Prisma и отправляют уже готовый HTML клиенту. Клиентские компоненты отвечают за интерактивные элементы: редактор юнита, форму сдачи теста, прогресс-бар, уведомления."),
      empty(),
      body("Файловая маршрутизация App Router строится на структуре директорий src/app/: каждая папка соответствует URL-сегменту, файл page.tsx — странице, route.ts — API-обработчику, layout.tsx — общему макету. Динамические сегменты оформляются как [id] или [unitId]. Это позволяет строить URL вроде /courses/[id]/stats/[studentId] без дополнительной конфигурации."),
      empty(),
      body("TypeScript", { bold: true, noIndent: true }),
      empty(),
      body("TypeScript — статически типизированное надмножество JavaScript, разработанное Microsoft. В проекте TypeScript используется на всех уровнях: типы Prisma-моделей (автогенерируются из схемы), интерфейсы пропсов компонентов, типы ответов API-маршрутов, параметры хуков. Это позволяет находить ошибки несоответствия типов на этапе компиляции, а не в рантайме — особенно ценно для сложных операций с данными прогресса, попытками тестов и ответами."),
      empty(),
      body("Prisma ORM", { bold: true, noIndent: true }),
      empty(),
      body("Prisma — современный ORM для Node.js с декларативной схемой. Файл prisma/schema.prisma описывает все модели данных и их связи. Команда npx prisma generate создаёт типизированный клиент PrismaClient на основе схемы. Команда npx prisma migrate dev генерирует и применяет SQL-миграции. Prisma Studio предоставляет веб-интерфейс для просмотра и редактирования данных в базе."),
      empty(),
      body("Особенностью Prisma является поддержка операции upsert (вставка или обновление), которая широко используется в SkillHub для сохранения прогресса студентов: если запись прогресса уже существует — она обновляется, если нет — создаётся. Это гарантирует идемпотентность операций и предотвращает дублирование."),
      empty(),
      body("PostgreSQL (Neon)", { bold: true, noIndent: true }),
      empty(),
      body("PostgreSQL — реляционная СУБД, мировой стандарт для продакшн-приложений. В проекте используется облачный хостинг Neon — serverless PostgreSQL с автоматическим масштабированием до нуля при отсутствии запросов. Neon предоставляет два URL подключения: прямое (для миграций) и через пул pgBouncer (для серверных функций Vercel, где каждый вызов создаёт новое соединение). В schema.prisma настраивается параметр directUrl для корректного выполнения npx prisma migrate."),
      empty(),
      body("В схеме базы данных активно используются составные уникальные индексы (например, @@unique([userId, unitId]) в UnitProgress), составные индексы (@@index([userId, courseId])) и каскадное удаление (onDelete: Cascade) для поддержания целостности данных при удалении курсов или пользователей."),
      empty(),
      body("Tailwind CSS", { bold: true, noIndent: true }),
      empty(),
      body("Tailwind CSS — утилитарный CSS-фреймворк, где стили задаются непосредственно в JSX через классы (flex, gap-4, rounded-2xl, bg-white). Это устраняет необходимость в отдельных CSS-файлах, ускоряет разработку и предотвращает конфликты имён классов. В SkillHub реализована дизайн-система на основе CSS-переменных (--accent, --surface-muted, --muted), что позволяет централизованно менять цветовую схему. Для кастомных компонентов используются классы-утилиты skillhub-panel, skillhub-hero, skillhub-chip, определённые в globals.css."),
      empty(),
      body("NextAuth.js", { bold: true, noIndent: true }),
      empty(),
      body("NextAuth.js (в проекте — auth-providers на основе библиотеки jose) реализует аутентификацию по email и паролю. Пароль хэшируется через bcrypt перед сохранением в поле passwordHash. При входе функция getSessionUser() декодирует JWT-токен из cookies и возвращает объект пользователя с id, email, name и role. Функция requireUser() аналогична, но выбрасывает redirect на страницу входа при отсутствии авторизации. Роли (STUDENT, TEACHER, ADMIN) используются для проверки прав доступа в каждом API-маршруте и серверном компоненте."),
      empty(),
      body("LiveKit", { bold: true, noIndent: true }),
      empty(),
      body("LiveKit — WebRTC-платформа с открытым исходным кодом для видеозвонков в реальном времени. Сервер LiveKit Cloud управляет SFU (Selective Forwarding Unit), обеспечивая низкую задержку (<200 мс) и адаптивный битрейт. Каждый участник получает JWT-токен с указанием имени комнаты и набора прав (публикация видео/аудио, подписка на других участников). В SkillHub используется пакет @livekit/components-react, предоставляющий готовые компоненты: VideoConference для отображения плиток участников, ControlBar для управления микрофоном и камерой, Chat для текстового чата внутри занятия."),
      empty(),

      heading2("Применяемые подходы к обучению", "1.3"),
      empty(),
      body("При проектировании SkillHub были изучены и реализованы несколько педагогических подходов, которые в совокупности формируют эффективную образовательную среду."),
      empty(),
      heading3("Микрообучение (Microlearning)", "1.3.1"),
      empty(),
      body("Микрообучение строится на принципе подачи учебного материала небольшими, логически завершёнными блоками длительностью 5–15 минут. Нейронаучные исследования подтверждают, что рабочая память человека способна эффективно обрабатывать ограниченный объём новой информации за один сеанс — принцип, известный как «число Миллера» (7 ± 2 единицы информации). Дробление материала на короткие занятия снижает когнитивную нагрузку и улучшает долгосрочное запоминание."),
      empty(),
      body("В SkillHub иерархия «курс → модуль → занятие (юнит)» непосредственно отражает принцип микрообучения. Каждый юнит (модель LessonUnit) содержит один конкретный учебный элемент: текстовый материал (MATERIAL), видеоурок (VIDEO), тест (TEST) или живое занятие (LIVE). Преподаватель создаёт контент небольшими блоками, что дисциплинирует структуру курса. Студент может изучить один юнит за перерыв и отметить его пройденным, наблюдая визуальный прогресс в прогресс-баре курса."),
      empty(),
      heading3("Смешанное обучение (Blended Learning)", "1.3.2"),
      empty(),
      body("Смешанное обучение объединяет асинхронный и синхронный форматы. Асинхронный формат позволяет студентам изучать материалы в удобное время и темп, синхронный — обеспечивает живое взаимодействие с преподавателем для разбора сложных тем и получения немедленной обратной связи."),
      empty(),
      body("В SkillHub асинхронная составляющая реализована через юниты с материалами, видео, тестами и домашними заданиями. Синхронная — через систему видеозвонков на базе LiveKit: преподаватель создаёт CallSession (или привязанный к курсу Lesson типа LIVE), генерирует уникальный invite-токен и делится ссылкой со студентом. Совместная интерактивная доска (BoardDocument) позволяет рисовать, объяснять схемы и решать задачи в реальном времени в ходе видеосессии. Такая комбинация даёт студентам гибкость самостоятельного обучения при сохранении ценности живого преподавательского контакта."),
      empty(),
      heading3("Отслеживание прогресса (Progress Tracking)", "1.3.3"),
      empty(),
      body("Регулярная обратная связь о собственном прогрессе является мощным мотивационным фактором. Когда учащийся видит, что он продвигается к цели — завершил 6 из 10 занятий, набрал 85% на последнем тесте, — у него формируется ощущение компетентности, что согласуется с теорией самодетерминации Деси и Райана."),
      empty(),
      body("В SkillHub прогресс реализован двухуровнево. На клиенте хук useCourseProgress хранит состояние в localStorage под ключом skillhub:course-progress, что обеспечивает мгновенное обновление интерфейса без задержки сети. На сервере модель UnitProgress в PostgreSQL фиксирует статус (IN_PROGRESS / COMPLETED), процент прохождения, время первого посещения и время завершения. Синхронизация происходит через PATCH-запрос к /api/units/[unitId]/progress в режиме fire-and-forget: даже при сбое сети прогресс не теряется на клиенте и будет синхронизирован при следующем сеансе."),
      empty(),
      heading3("Формирующее оценивание (Formative Assessment)", "1.3.4"),
      empty(),
      body("Формирующее оценивание предполагает регулярную проверку знаний с немедленной обратной связью на протяжении всего курса, в отличие от итогового оценивания (экзамена в конце). Исследования Блэка и Уильяма показали, что грамотно выстроенное формирующее оценивание повышает успеваемость учащихся эффективнее большинства других педагогических вмешательств."),
      empty(),
      body("В SkillHub после завершения попытки теста студент немедленно видит разбор: правильные ответы выделены зелёным, выбранные неверные — красным. Для открытых вопросов отображается эталонный ответ (поле correctText в TestQuestion). Тест можно пересдать — засчитывается лучший результат. Домашние задания обеспечивают ещё один канал обратной связи: преподаватель оставляет письменный комментарий и оценку (0–100), после чего студент видит разбор своей работы прямо на странице занятия."),
      empty(),

      // ── ГЛАВА 2 ────────────────────────────────
      pageBreak(),
      heading1("Разработка платформы для онлайн-обучения", "2"),
      empty(),
      heading2("Архитектура приложения и модели данных", "2.1"),
      empty(),
      body("Общая структура проекта", { bold: true, noIndent: true }),
      empty(),
      body("Приложение организовано по принципам Feature-Sliced Design (FSD), адаптированным под структуру Next.js App Router. Кодовая база разделена на следующие директории верхнего уровня:"),
      bullet("src/app/ — маршруты приложения. Каждая поддиректория соответствует URL-сегменту. Файлы page.tsx — серверные компоненты-страницы; route.ts — API Route Handlers; layout.tsx — общие макеты для группы страниц."),
      bullet("src/features/ — функциональные модули (courses, lesson, calls, dashboard, profile, tests). Каждый содержит поддиректории ui/ (компоненты), lib/ (хуки и утилиты)."),
      bullet("src/components/ — переиспользуемые компоненты: SiteHeader, NotificationBell и другие."),
      bullet("src/lib/ — вспомогательные модули: db.ts (экземпляр PrismaClient), auth.ts (getSessionUser, requireUser)."),
      bullet("prisma/ — файл schema.prisma со схемой БД и директория migrations/ с историей миграций."),
      bullet("public/uploads/ — файлы, загружаемые пользователями (изображения курсов, материалы занятий)."),
      empty(),
      body("Маршрутизация приложения", { bold: true, noIndent: true }),
      empty(),
      body("Публичные маршруты (не требуют авторизации): / (главная страница), /auth/login, /auth/register. Защищённые маршруты автоматически перенаправляют неавторизованного пользователя через requireUser(). Ключевые маршруты приложения:"),
      bullet("/dashboard — дашборд пользователя (список своих и записанных курсов, предстоящие занятия)."),
      bullet("/courses — каталог всех курсов."),
      bullet("/courses/[id] — страница конкретного курса с картой модулей и юнитов."),
      bullet("/courses/[id]/stats — статистика курса для преподавателя."),
      bullet("/courses/[id]/stats/[studentId] — детальная статистика конкретного студента."),
      bullet("/learn/[unitId] — страница занятия (студент): материал, видео, тест, домашнее задание."),
      bullet("/tests/[id] — прохождение теста и просмотр результатов."),
      bullet("/tests/[id]/review — разбор попытки теста."),
      bullet("/homework/[id] — страница домашнего задания."),
      bullet("/profile — личный кабинет (настройки профиля)."),
      bullet("/calls/[roomName] — страница видеозвонка через LiveKit."),
      empty(),
      body("Модели данных (Prisma-схема)", { bold: true, noIndent: true }),
      empty(),
      body("Схема базы данных содержит 18 моделей и 4 перечисления. Рассмотрим их подробно."),
      empty(),
      body("User — центральная сущность системы. Хранит id (CUID), имя, уникальный email, хэш пароля (bcrypt), роль (STUDENT / TEACHER / ADMIN), временны́е метки createdAt и updatedAt. Связан с записями на курсы (enrollments), преподаваемыми курсами (taughtCourses), прогрессом по юнитам (unitProgress), попытками тестов (testAttempts), ответами на вопросы (testAnswers), сдачами домашних заданий (submissions), видеозанятиями как преподаватель (taughtCalls) и как студент (studentCalls), сообщениями (messages, callMessages) и состоянием доски (boardAsTeacher, boardAsStudent)."),
      empty(),
      body("Course — учебный курс. Хранит id, название (title), описание (description), ссылку на изображение-обложку (imageUrl), признак публикации (isPublished), id преподавателя (teacherId). Связан с модулями (modules), записями студентов (enrollments), домашними заданиями (homeworks), тестами (tests) и прогрессом (unitProgress)."),
      empty(),
      body("CourseModule — модуль курса (тематический раздел). Хранит id, id курса (courseId), название (title), порядковую позицию (position). Содержит список юнитов (units). Порядок модулей определяется полем position, что позволяет преподавателю переставлять модули."),
      empty(),
      body("LessonUnit — занятие (юнит) внутри модуля. Хранит id, id модуля (moduleId), название (title), описание (description), позицию (position), тип (unitType: MATERIAL / VIDEO / TEST / LIVE), опциональную ссылку на Lesson для живых уроков (lessonId). Связан с LessonMaterial (контент), UnitAttachment (вложения), Test (тесты), UnitProgress (прогресс студентов)."),
      empty(),
      body("LessonMaterial — содержимое юнита. Хранит id, id юнита (unitId), текстовый контент в формате Markdown (content), структурированный контент в JSON (contentJson), URL видео (videoUrl). Связь один-к-одному с LessonUnit."),
      empty(),
      body("UnitAttachment — файл, прикреплённый к юниту. Хранит id, id юнита (unitId), имя файла (name), URL (url), тип (AttachmentType: FILE / IMAGE), размер в байтах (size). Файлы IMAGE встраиваются в текст через Markdown-синтаксис, FILE отображаются как ссылки для скачивания."),
      empty(),
      body("UnitProgress — прогресс студента по конкретному юниту. Хранит id, id пользователя (userId), id юнита (unitId), id курса (courseId), статус (IN_PROGRESS / COMPLETED), процент прохождения (progressPercent 0–100), время начала (startedAt), время завершения (completedAt), время последнего визита (lastVisitedAt). Уникальность обеспечена составным индексом @@unique([userId, unitId]). Дополнительные индексы @@index([userId, courseId]) и @@index([courseId, status]) ускоряют выборку для аналитики."),
      empty(),
      body("Test — тест, привязанный к юниту или уроку. Хранит id, название (title), описание (description), опциональные ссылки на курс/урок/юнит, id создателя (createdById), признак публикации (isPublished). Содержит вопросы (questions) и попытки прохождения (attempts)."),
      empty(),
      body("TestQuestion — вопрос теста. Хранит id, id теста (testId), текст вопроса (question), тип (TestQuestionType: SINGLE / MULTI / OPEN), порядок (position), количество баллов (points), эталонный ответ для открытых вопросов (correctText). Содержит варианты ответа (options) и ответы студентов (answers)."),
      empty(),
      body("TestOption — вариант ответа на вопрос. Хранит id, id вопроса (questionId), текст (text), признак правильности (isCorrect), позицию (position)."),
      empty(),
      body("TestAttempt — попытка прохождения теста. Хранит id, id теста (testId), id студента (studentId), время начала (startedAt), время сдачи (submittedAt — null для незавершённых), набранный балл (score), максимальный балл (maxScore), признак необходимости проверки преподавателем (requiresReview — для открытых вопросов). Содержит ответы студента (answers)."),
      empty(),
      body("TestAnswer — ответ студента на один вопрос в рамках попытки. Хранит id, id попытки (attemptId), id вопроса (questionId), id автора (authorId), массив id выбранных вариантов (selectedOptionIds), текстовый ответ (textAnswer), признак правильности (isCorrect), набранные баллы (score)."),
      empty(),
      body("Homework — домашнее задание, прикреплённое к уроку и курсу. Хранит id, id урока (lessonId), id курса (courseId), id автора (authorId), название (title), описание (description), срок сдачи (dueDate — опционально). Содержит сдачи студентов (submissions)."),
      empty(),
      body("HomeworkSubmission — сдача домашнего задания студентом. Хранит id, id задания (homeworkId), id студента (studentId), текст ответа (content), статус (submitted / reviewed), оценку (grade, 0–100), комментарий преподавателя (comment). Уникальность — @@unique([homeworkId, studentId]) — обеспечивает одну сдачу от студента на задание."),
      empty(),
      body("Lesson — видеозанятие в расписании курса. Хранит id, название (title), время начала (startsAt), длительность (durationMins), id курса (courseId), уникальное имя LiveKit-комнаты (roomName). Связан с участниками (participants), сообщениями чата (messages), домашними заданиями (homeworks), состоянием доски (room: LessonRoom) и юнитом курса (unit: LessonUnit)."),
      empty(),
      body("CallSession — персональный видеозвонок преподавателя со студентом (формат «один на один»). Хранит id, id преподавателя (teacherId), id студента (studentId), уникальный invite-токен (inviteToken), статус (SCHEDULED / ACTIVE / ENDED / CANCELLED), тему (topic), запланированное время (scheduledAt), фактическое начало/конец (startedAt / endedAt), имя LiveKit-комнаты (livekitRoomName). Содержит сообщения чата (messages: CallMessage[])."),
      empty(),
      body("BoardDocument — состояние совместной доски для пары преподаватель–студент. Хранит id, teacherId, studentId, состояние доски в JSON (boardState), временны́е метки. Уникальность @@unique([teacherId, studentId]) означает одну доску на пару."),
      empty(),
      caption("Рис. 1 – ERD-диаграмма базы данных SkillHub (упрощённая)"),
      empty(),

      heading2("База данных и серверная логика (API Routes)", "2.2"),
      empty(),
      body("Подключение к базе данных", { bold: true, noIndent: true }),
      empty(),
      body("В файле src/lib/db.ts создаётся единственный экземпляр PrismaClient, сохраняемый в глобальной переменной в режиме разработки (для предотвращения множества соединений при горячей перезагрузке модулей):"),
      empty(),
      codeBlock([
        'import { PrismaClient } from "@prisma/client";',
        '',
        'const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };',
        '',
        'export const db =',
        '  globalForPrisma.prisma ?? new PrismaClient({ log: ["error"] });',
        '',
        'if (process.env.NODE_ENV !== "production")',
        '  globalForPrisma.prisma = db;',
      ]),
      empty(),
      body("В продакшн-окружении Vercel каждый serverless-вызов создаёт отдельный экземпляр, соединение идёт через pgBouncer Neon, что предотвращает исчерпание пула соединений PostgreSQL."),
      empty(),
      body("Структура API Routes", { bold: true, noIndent: true }),
      empty(),
      body("Проект содержит более 40 API Route Handler-ов в директории src/app/api/. Каждый файл route.ts экспортирует именованные HTTP-обработчики (GET, POST, PATCH, DELETE). Аутентификация проверяется в начале каждого обработчика через getSessionUser(). Рассмотрим ключевые маршруты."),
      empty(),
      body("Аутентификация (/api/auth/):", { bold: true, noIndent: true }),
      bullet("POST /api/auth/register — создаёт нового пользователя: проверяет уникальность email, хэширует пароль через bcrypt с saltRounds=12, сохраняет запись User, генерирует JWT и устанавливает cookie."),
      bullet("POST /api/auth/login — проверяет email и пароль (bcrypt.compare), генерирует JWT с payload {id, email, name, role}, устанавливает httpOnly cookie."),
      bullet("POST /api/auth/logout — удаляет cookie сессии."),
      empty(),
      body("Управление курсами:", { bold: true, noIndent: true }),
      bullet("GET /api/courses — возвращает список всех курсов с информацией о преподавателе и количестве записанных студентов."),
      bullet("POST /api/courses — создаёт новый курс (только TEACHER или ADMIN)."),
      bullet("GET/PATCH/DELETE /api/courses/[id] — получение, обновление и удаление конкретного курса."),
      bullet("POST /api/courses/[id]/enroll — запись текущего пользователя на курс."),
      bullet("GET/POST /api/courses/[id]/modules — список модулей курса / создание нового модуля."),
      empty(),
      body("Управление юнитами и прогрессом:", { bold: true, noIndent: true }),
      bullet("GET/PATCH/DELETE /api/units/[unitId] — получение, обновление и удаление юнита."),
      bullet("GET/PATCH /api/units/[unitId]/material — получение и сохранение содержимого юнита (Markdown-текст, видео-URL)."),
      bullet("POST /api/units/[unitId]/attachments — загрузка вложения к юниту."),
      bullet("DELETE /api/units/[unitId]/attachments/[attachmentId] — удаление вложения."),
      bullet("PATCH /api/units/[unitId]/progress — сохранение прогресса студента по юниту."),
      empty(),
      body("Пример обработчика PATCH /api/units/[unitId]/progress с реальной логикой проекта:"),
      empty(),
      codeBlock([
        'export async function PATCH(',
        '  request: Request,',
        '  { params }: { params: Promise<{ unitId: string }> },',
        ') {',
        '  const user = await getSessionUser();',
        '  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });',
        '',
        '  const { unitId } = await params;',
        '  const unit = await db.lessonUnit.findUnique({',
        '    where: { id: unitId },',
        '    select: { id: true, module: { select: { courseId: true } } },',
        '  });',
        '  if (!unit) return NextResponse.json({ error: "Not found" }, { status: 404 });',
        '',
        '  const { status, progressPercent } = await request.json();',
        '  const progressStatus = status === "completed"',
        '    ? UnitProgressStatus.COMPLETED',
        '    : UnitProgressStatus.IN_PROGRESS;',
        '  const percent = Math.max(0, Math.min(100, Math.round(progressPercent ?? 0)));',
        '',
        '  const record = await db.unitProgress.upsert({',
        '    where: { userId_unitId: { userId: user.id, unitId } },',
        '    create: { userId: user.id, unitId,',
        '      courseId: unit.module.courseId, status: progressStatus,',
        '      progressPercent: percent, startedAt: new Date() },',
        '    update: { status: progressStatus, progressPercent: percent,',
        '      lastVisitedAt: new Date(),',
        '      completedAt: progressStatus === "COMPLETED" ? new Date() : undefined },',
        '  });',
        '  return NextResponse.json(record);',
        '}',
      ]),
      empty(),
      body("Тесты и попытки:", { bold: true, noIndent: true }),
      bullet("GET/POST /api/tests — список тестов / создание теста."),
      bullet("GET/PATCH/DELETE /api/tests/[id] — управление тестом."),
      bullet("GET/POST /api/tests/[id]/questions — вопросы теста / добавление вопроса."),
      bullet("GET/PATCH/DELETE /api/questions/[id] — управление вопросом (и его вариантами ответа)."),
      bullet("POST /api/tests/[id]/attempts — создание новой попытки (или возврат открытой, если студент уже начал тест)."),
      bullet("POST /api/attempts/[id]/submit — завершение попытки: проверка ответов, вычисление баллов, сохранение score."),
      bullet("PATCH /api/attempts/[id]/grade — ручная проверка открытых ответов преподавателем."),
      empty(),
      body("Загрузка файлов:", { bold: true, noIndent: true }),
      body("POST /api/upload принимает multipart/form-data с полем file. Файл сохраняется в public/uploads/ под UUID-именем с сохранением расширения оригинального файла. В ответе возвращается объект {url, name, size, type}, после чего клиент сохраняет запись UnitAttachment через /api/units/[unitId]/attachments."),
      empty(),
      caption("Рис. 2 – Схема взаимодействия клиента, Next.js App Router и базы данных"),
      empty(),

      heading2("Реализация функционала курсов и уроков", "2.3"),
      empty(),
      body("Страница курса", { bold: true, noIndent: true }),
      empty(),
      body("Файл src/app/courses/[id]/page.tsx — серверный компонент. При каждом запросе он выполняет единственный запрос к базе данных через Prisma с подгрузкой всех связанных данных (include): преподаватель, записи студентов, модули, юниты каждого модуля и тесты каждого юнита. Это N+1-безопасный подход благодаря Prisma Include, который генерирует JOIN-запросы."),
      empty(),
      body("На основе полученных данных вычисляются агрегаты: totalUnits, totalTests, totalLive, totalMaterials. Страница отображает «hero»-баннер с названием и описанием курса, сетку с ключевыми метриками (материалы, live-уроки, тесты, статус записи), прогресс-бар (если студент записан), кнопку статистики (если пользователь — преподаватель или администратор), карту курса в виде списка модулей с юнитами и навигационный сайдбар CourseProgramSidebar."),
      empty(),
      body("Типы юнитов", { bold: true, noIndent: true }),
      empty(),
      body("Перечисление UnitType определяет четыре вида занятий:"),
      bullet("MATERIAL — текстовый или смешанный юнит: Markdown-текст с возможностью встраивания изображений, прикреплённые файлы для скачивания."),
      bullet("VIDEO — видеоурок: ссылка на внешний видеохостинг (YouTube, Vimeo или загруженный файл), текстовые заметки."),
      bullet("TEST — тест как самостоятельный юнит (без дополнительного текстового содержимого, только Test-объект)."),
      bullet("LIVE — живой урок: юнит привязан к Lesson с roomName и расписанием startsAt."),
      empty(),
      body("Редактор юнита (UnitEditor)", { bold: true, noIndent: true }),
      empty(),
      body("Компонент UnitEditor.tsx (src/features/courses/ui/) предоставляет преподавателю интерфейс редактирования содержимого занятия. Текстовое поле (textarea) поддерживает Markdown с предварительным просмотром. Кнопка «Вставить картинку» открывает диалог выбора файла; после загрузки через /api/upload и сохранения вложения в базе формируется строка ![название](url) и вставляется в позицию курсора через selectionStart/selectionEnd:"),
      empty(),
      codeBlock([
        'function insertAtCursor(url: string, name: string) {',
        '  const ta = contentRef.current;',
        '  if (!ta) return;',
        '  const start = ta.selectionStart;',
        '  const end   = ta.selectionEnd;',
        '  const md    = `![${name}](${url})`;',
        '  const next  = content.slice(0, start) + md + content.slice(end);',
        '  setContent(next);',
        '  requestAnimationFrame(() => {',
        '    ta.selectionStart = ta.selectionEnd = start + md.length;',
        '    ta.focus();',
        '  });',
        '}',
      ]),
      empty(),
      body("Документальные файлы (PDF, Word и др.) отображаются отдельным разделом «Материалы» над текстом занятия как кликабельные ссылки для скачивания с иконкой типа файла и размером."),
      empty(),
      body("Редактор тестов (TestsEditor)", { bold: true, noIndent: true }),
      empty(),
      body("Компонент TestsEditor.tsx позволяет добавлять и редактировать тесты в рамках занятия. Для каждого теста можно добавить неограниченное количество вопросов трёх типов. Для вопросов SINGLE и MULTI создаются варианты ответа (TestOption), один или несколько из которых отмечаются флажком «Верный ответ». Для вопросов типа OPEN задаётся поле correctText — эталонный ответ, который студент увидит после сдачи. Порядок вопросов определяется полем position и может быть изменён перетаскиванием."),
      empty(),
      body("Страница занятия для студента", { bold: true, noIndent: true }),
      empty(),
      body("Файл src/app/learn/[unitId]/page.tsx — серверный компонент, загружающий данные юнита с материалом, вложениями, тестами и домашними заданиями. Контент отображается в следующем порядке: вложенные файлы → Markdown-текст (через ReactMarkdown с кастомным рендерером img) → видео → тест → домашнее задание. Компонент MarkdownContent.tsx рендерит изображения с rounded-2xl, подписью и опциональным увеличением по клику."),
      empty(),
      caption("Рис. 3 – Страница занятия: вложения, Markdown-текст с изображением, тест, ДЗ"),
      empty(),

      heading2("Система прогресса и статистики", "2.4"),
      empty(),
      body("Клиентское состояние прогресса", { bold: true, noIndent: true }),
      empty(),
      body("Прогресс хранится в localStorage браузера под ключом skillhub:course-progress:v1:{courseId} в формате JSON-объекта CourseProgressState, где каждый ключ — id юнита, значение — объект {status, progressPercent, startedAt, completedAt}."),
      empty(),
      body("Хук useCourseProgress (src/features/courses/lib/useCourseProgress.ts) инкапсулирует всю логику работы с прогрессом. Он подписывается на три события браузера для синхронизации между вкладками:"),
      bullet("storage — обновляет состояние при изменении localStorage в другой вкладке."),
      bullet("focus — обновляет при возврате фокуса на вкладку (пользователь переключился и вернулся)."),
      bullet("visibilitychange — обновляет при переходе страницы из скрытого в видимое состояние."),
      empty(),
      body("Функция syncProgressToDb выполняет fire-and-forget PATCH-запрос на /api/units/[unitId]/progress: ошибки сети перехватываются через .catch(() => null) и не блокируют UI. Это решение обеспечивает оптимистичное обновление интерфейса — кнопка «Завершено» меняет состояние мгновенно, независимо от скорости соединения."),
      empty(),
      body("Пример вызова при завершении занятия:"),
      empty(),
      codeBlock([
        'const markCompleted = useCallback((unitId: string) => {',
        '  const result = markUnitCompleted(courseId, unitId);  // localStorage',
        '  syncProgressToDb(unitId, "completed", 100);          // DB fire-and-forget',
        '  refresh();                                           // перерендер',
        '  return result;',
        '}, [courseId, refresh]);',
      ]),
      empty(),
      body("Прогресс-бар курса", { bold: true, noIndent: true }),
      empty(),
      body("Компонент CourseProgressBar вычисляет процент завершённых юнитов по формуле: (количество юнитов со статусом completed) / (общее количество юнитов) × 100. Визуально отображается как горизонтальная полоса с акцентным цветом и подписью «X из N занятий». Компонент является клиентским, так как читает localStorage, — серверный компонент страницы передаёт ему только список id юнитов."),
      empty(),
      body("Страница статистики курса", { bold: true, noIndent: true }),
      empty(),
      body("Маршрут /courses/[id]/stats доступен только пользователям с ролью TEACHER (если они автор курса) или ADMIN. Серверный компонент выполняет несколько Prisma-запросов:"),
      bullet("Список записанных студентов с их прогрессом (UnitProgress), попытками тестов (TestAttempt) и домашними заданиями (HomeworkSubmission)."),
      bullet("Список всех тестов курса с агрегатами: количество попыток, средний балл, количество незавершённых работ."),
      bullet("Список всех домашних заданий курса с агрегатами: количество сдач, средняя оценка."),
      empty(),
      body("Сводная таблица студентов (StudentsTable.tsx) отображает для каждого: аватар с инициалами, имя, email, процент прогресса, количество пройденных/всего тестов, средний балл по тестам, количество проверенных/всего домашних заданий. При клике на строку студента открывается детальная страница /courses/[id]/stats/[studentId]."),
      empty(),
      body("Детальная страница статистики студента отображает:", { noIndent: true }),
      bullet("Прогресс по каждому занятию: зелёный индикатор (COMPLETED), оранжевый (IN_PROGRESS), серый (не открывал), с датами начала и завершения."),
      bullet("Разбор каждого теста: вопрос, варианты ответа с цветовой подсветкой (зелёный — правильный, красный — выбранный неправильный, серый — невыбранный правильный), набранный балл."),
      bullet("Домашние задания: текст ответа студента, статус, оценка, комментарий преподавателя, кнопка «Проверить ДЗ» для незавершённых работ."),
      empty(),
      caption("Рис. 4 – Детальная страница статистики студента: прогресс, тесты, ДЗ"),
      empty(),

      heading2("Видеозвонки, совместная доска и домашние задания", "2.5"),
      empty(),
      body("Система видеозвонков", { bold: true, noIndent: true }),
      empty(),
      body("В SkillHub реализованы два формата видеозанятий. Первый — групповой Lesson, привязанный к курсу: преподаватель создаёт занятие с расписанием (startsAt, durationMins), к нему присоединяются все записанные студенты курса. Второй — персональный CallSession между преподавателем и конкретным студентом (формат «один на один»)."),
      empty(),
      body("Жизненный цикл CallSession описывается четырьмя статусами:"),
      bullet("SCHEDULED — сессия создана, время ещё не наступило."),
      bullet("ACTIVE — занятие идёт в реальном времени."),
      bullet("ENDED — занятие завершено нормально."),
      bullet("CANCELLED — отменено преподавателем или студентом."),
      empty(),
      body("При создании CallSession сервер генерирует уникальный inviteToken (UUID) и уникальное имя LiveKit-комнаты (livekitRoomName). Преподаватель делится ссылкой вида /calls/invite/[token] со студентом. При переходе по ссылке студент видит страницу подтверждения с темой занятия и кнопкой «Присоединиться». При нажатии выполняется запрос к /api/calls/invite/[token], сервер возвращает данные сессии и автоматически перенаправляет на страницу видеозвонка."),
      empty(),
      body("JWT-токен для LiveKit генерируется на сервере в маршруте /api/calls/[id]/livekit-token с использованием SDK livekit-server-sdk. Преподаватель получает токен с правами CanPublish, CanSubscribe, RoomAdmin; студент — CanPublish, CanSubscribe. Это разграничивает возможность управления комнатой (выключить микрофон участника, завершить занятие для всех)."),
      empty(),
      body("Клиентский компонент CallVideoRoom.tsx использует @livekit/components-react:"),
      empty(),
      codeBlock([
        'import { LiveKitRoom, VideoConference } from "@livekit/components-react";',
        '',
        'export function CallVideoRoom({ token, serverUrl }) {',
        '  return (',
        '    <LiveKitRoom token={token} serverUrl={serverUrl}',
        '      data-lk-theme="default" style={{ height: "100dvh" }}>',
        '      <VideoConference />',
        '    </LiveKitRoom>',
        '  );',
        '}',
      ]),
      empty(),
      body("Компонент VideoConference автоматически управляет плитками видео участников, адаптирует сетку под число подключённых пользователей и предоставляет ControlBar с кнопками выключения микрофона/камеры, демонстрации экрана и выхода из комнаты."),
      empty(),
      body("Совместная интерактивная доска", { bold: true, noIndent: true }),
      empty(),
      body("Модель BoardDocument обеспечивает персистентное хранение состояния совместной доски для пары преподаватель–студент. Поле boardState хранит JSON-сериализованное состояние инструмента рисования (координаты линий, текстовые блоки, фигуры). Маршрут GET/PATCH /api/calls/[id]/board и /api/lessons/[id]/board позволяют загружать и сохранять состояние в реальном времени. При каждом изменении доски клиент отправляет PATCH с новым boardState — таким образом преподаватель и студент всегда видят актуальное состояние после перезагрузки страницы."),
      empty(),
      body("Система домашних заданий", { bold: true, noIndent: true }),
      empty(),
      body("Homework создаётся преподавателем в рамках занятия (Lesson). В модели хранятся: заголовок задания, подробное описание с инструкциями, опциональный срок сдачи (dueDate). На странице занятия студент видит раздел «Домашнее задание» с условием и текстовым полем для ответа."),
      empty(),
      body("При нажатии «Отправить» выполняется POST /api/homework/[id]/submissions с телом {content: «текст ответа»}. Сервер создаёт запись HomeworkSubmission со статусом submitted. Повторная отправка обновляет существующую запись через upsert по @@unique([homeworkId, studentId])."),
      empty(),
      body("Преподаватель проверяет работы на детальной странице статистики студента. Форма проверки отправляет PATCH /api/homework/submissions/[id] с {grade: number, comment: string}. После сохранения статус меняется на reviewed, студент видит оценку и комментарий при следующем открытии страницы занятия."),
      empty(),
      caption("Рис. 5 – Интерфейс видеозанятия (LiveKit) и форма проверки домашнего задания"),
      empty(),

      heading2("Деплой и инфраструктура", "2.6"),
      empty(),
      body("Vercel", { bold: true, noIndent: true }),
      empty(),
      body("Приложение задеплоено на Vercel — облачную платформу, разработанную создателями Next.js. Vercel обеспечивает автоматический CI/CD: при каждом push в ветку main GitHub Actions-триггер запускает сборку на серверах Vercel. Сборка включает:"),
      bullet("Установку зависимостей (npm ci)."),
      bullet("Генерацию Prisma-клиента (npx prisma generate)."),
      bullet("Компиляцию TypeScript и Next.js (next build)."),
      bullet("Деплой собранных серверных функций на Edge Network Vercel (глобальная CDN)."),
      empty(),
      body("Vercel автоматически разделяет статические ресурсы (JS, CSS, изображения) и серверные функции (Route Handlers). Статика раздаётся с ближайшего CDN-узла, серверные функции выполняются в serverless-окружении Node.js 20. Каждая Route Handler — это независимая функция, масштабируемая горизонтально без дополнительной настройки."),
      empty(),
      body("Neon PostgreSQL", { bold: true, noIndent: true }),
      empty(),
      body("База данных размещена в Neon — serverless PostgreSQL-сервисе. Основная особенность Neon — автоматическое масштабирование до нуля при отсутствии запросов в течение нескольких минут. Это значительно снижает стоимость для учебного проекта (бесплатный тариф Neon позволяет обслуживать проект без платы). Единственный недостаток — «холодный старт» (~500 мс при пробуждении). Prisma обрабатывает это автоматически через retry-логику при первом подключении."),
      empty(),
      body("Для работы в serverless-среде Vercel необходим пул соединений pgBouncer. В schema.prisma задаются два URL:"),
      empty(),
      codeBlock([
        'datasource db {',
        '  provider  = "postgresql"',
        '  url       = env("DATABASE_URL")      // через pgBouncer (для app)',
        '  directUrl = env("DIRECT_URL")        // прямое (для migrations)',
        '}',
      ]),
      empty(),
      body("Переменные окружения", { bold: true, noIndent: true }),
      empty(),
      body("Чувствительные данные хранятся исключительно в настройках проекта Vercel и недоступны в репозитории. Ключевые переменные:"),
      bullet("DATABASE_URL — строка подключения к Neon через pgBouncer."),
      bullet("DIRECT_URL — прямое подключение к Neon для миграций."),
      bullet("NEXTAUTH_SECRET / JWT_SECRET — секрет для подписи JWT-токенов."),
      bullet("LIVEKIT_API_KEY, LIVEKIT_API_SECRET, LIVEKIT_URL — доступ к LiveKit Cloud."),
      bullet("NEXT_PUBLIC_LIVEKIT_URL — публичный URL для клиентского SDK."),
      empty(),
      body("Миграции базы данных", { bold: true, noIndent: true }),
      empty(),
      body("При изменении схемы (добавление модели, поля, индекса) разработчик выполняет npx prisma migrate dev --name «описание_изменения» локально. Prisma генерирует SQL-файл миграции в prisma/migrations/ и применяет его к локальной БД. В продакшн миграции применяются командой npx prisma migrate deploy, которую можно включить в Vercel Build Command для автоматического применения при каждом деплое."),
      empty(),
      caption("Рис. 6 – Схема деплоя: GitHub → Vercel → Neon PostgreSQL"),
      empty(),

      // ── ГЛАВА 3 ────────────────────────────────
      pageBreak(),
      heading1("Инструкция пользователя", "3"),
      empty(),
      body("Платформа SkillHub поддерживает три роли: Студент, Преподаватель и Администратор. Каждая роль имеет собственный интерфейс и набор доступных функций. Ниже подробно описан порядок работы для каждой роли."),
      empty(),

      heading2("Регистрация и вход в систему", "3.1"),
      empty(),
      body("Для начала работы с платформой необходимо создать учётную запись или войти в существующую."),
      empty(),
      body("Шаг 1. Откройте браузер и перейдите на главную страницу платформы. Вы увидите информационную страницу с описанием возможностей SkillHub."),
      empty(),
      body("Шаг 2. В правом верхнем углу страницы нажмите кнопку «Войти». Откроется страница аутентификации."),
      empty(),
      body("Шаг 3 (новый пользователь). Нажмите ссылку «Зарегистрироваться» под формой входа. Заполните поля: имя, адрес электронной почты, пароль (минимум 8 символов) и выберите роль — «Студент» или «Преподаватель». Нажмите кнопку «Создать аккаунт». После успешной регистрации вы автоматически будете перенаправлены на дашборд."),
      empty(),
      body("Шаг 3 (существующий пользователь). Введите email и пароль в форму входа. Нажмите «Войти». При успешной аутентификации вы будете перенаправлены на дашборд, соответствующий вашей роли."),
      empty(),
      body("Важно: если вы введёте неверный пароль трижды подряд, аккаунт не блокируется, но система отображает предупреждение. Для смены пароля перейдите в раздел «Профиль» → «Безопасность»."),
      empty(),
      caption("Рис. 7 – Страница входа и регистрации"),
      empty(),

      heading2("Работа в роли «Студент»", "3.2"),
      empty(),
      body("Дашборд студента", { bold: true, noIndent: true }),
      empty(),
      body("После входа вы попадаете на дашборд. На главном экране отображаются: ваши активные курсы с прогресс-барами, кнопка «Продолжить» для возобновления последнего курса, предстоящие видеозанятия с датой и временем, последние уведомления (оценки за домашние задания, комментарии преподавателя)."),
      empty(),
      body("Запись на курс", { bold: true, noIndent: true }),
      empty(),
      body("1. В верхнем меню перейдите в раздел «Каталог» или нажмите ссылку «Все курсы» на дашборде."),
      empty(),
      body("2. В каталоге отображаются все опубликованные курсы. Каждая карточка показывает: название, имя преподавателя, количество студентов и модулей."),
      empty(),
      body("3. Нажмите на карточку курса для открытия страницы с подробным описанием. Здесь отображаются: описание курса, статистика (количество материалов, live-уроков, тестов), карта модулей с перечнем занятий."),
      empty(),
      body("4. Нажмите кнопку «Записаться». Система создаёт запись Enrollment и курс появляется на вашем дашборде в разделе «Мои курсы»."),
      empty(),
      body("Изучение материала курса", { bold: true, noIndent: true }),
      empty(),
      body("1. На странице курса вы увидите прогресс-бар с указанием числа пройденных занятий и общего их количества."),
      empty(),
      body("2. На левой боковой панели (CourseProgramSidebar) отображается полная структура курса по модулям. Иконки рядом с занятиями обозначают тип: текстовый материал, видео или live-урок. Завершённые занятия подсвечиваются зелёным индикатором."),
      empty(),
      body("3. Нажмите на название занятия, чтобы перейти на страницу юнита. Контент отображается в следующем порядке:"),
      bullet("Прикреплённые файлы (если есть) — кликните для скачивания."),
      bullet("Текстовый материал в формате Markdown — включая заголовки, списки, таблицы и встроенные изображения."),
      bullet("Видео — встроенный плеер или ссылка на внешний ресурс."),
      bullet("Тест (если прикреплён) — раздел с кнопкой «Начать тест»."),
      bullet("Домашнее задание (если задано) — условие и форма для ответа."),
      empty(),
      body("Прохождение теста", { bold: true, noIndent: true }),
      empty(),
      body("1. Нажмите кнопку «Начать тест». Система создаёт новую попытку (TestAttempt) и переходит к режиму прохождения."),
      empty(),
      body("2. Для каждого вопроса выберите ответ. Типы вопросов:"),
      bullet("Одиночный выбор (SINGLE) — только один вариант может быть отмечен. Варианты отображаются как radio-кнопки."),
      bullet("Множественный выбор (MULTI) — несколько вариантов могут быть правильными. Варианты отображаются как флажки (checkbox)."),
      bullet("Открытый ответ (OPEN) — введите ответ в текстовое поле. Такие вопросы проверяются преподавателем вручную."),
      empty(),
      body("3. После ответа на все вопросы нажмите «Завершить тест». Система сохраняет попытку, автоматически проверяет вопросы с вариантами ответов и вычисляет итоговый балл."),
      empty(),
      body("4. На странице результатов отображаются:"),
      bullet("Итоговый балл (например, «85 из 100»)."),
      bullet("Разбор каждого вопроса: правильный ответ выделен зелёным фоном, выбранный неправильный — красным, невыбранный правильный — зелёной рамкой."),
      bullet("Для открытых вопросов — эталонный ответ преподавателя (если указан)."),
      empty(),
      body("5. Для повторного прохождения нажмите «Пройти заново». Система засчитывает лучший результат из всех попыток."),
      empty(),
      body("6. Детальный разбор попытки доступен по ссылке «Просмотреть разбор» → /tests/[id]/review."),
      empty(),
      body("Сдача домашнего задания", { bold: true, noIndent: true }),
      empty(),
      body("1. В нижней части страницы занятия найдите раздел «Домашнее задание». Прочитайте условие и срок сдачи (если указан)."),
      empty(),
      body("2. Введите ответ в текстовое поле. Ответ может содержать форматированный текст."),
      empty(),
      body("3. Нажмите «Отправить». Кнопка сменится на «Ответ отправлен» с датой отправки."),
      empty(),
      body("4. После проверки преподавателем на странице занятия появится блок с оценкой (число от 0 до 100) и письменным комментарием преподавателя. Уведомление о проверке также придёт в раздел уведомлений (колокольчик в шапке сайта)."),
      empty(),
      body("Отметка занятия как пройденного", { bold: true, noIndent: true }),
      empty(),
      body("1. После изучения материала нажмите кнопку «Отметить как пройденное» в правой части страницы занятия."),
      empty(),
      body("2. Кнопка изменится на зелёный баннер «Занятие пройдено ✓». Прогресс в прогресс-баре курса обновится."),
      empty(),
      body("3. Для перехода к следующему занятию нажмите «Завершить и продолжить →». Система записывает прогресс и перенаправляет на следующий юнит курса."),
      empty(),
      caption("Рис. 8 – Страница занятия (вид студента): прогресс, тест, кнопка завершения"),
      empty(),

      heading2("Работа в роли «Преподаватель»", "3.3"),
      empty(),
      body("Создание курса", { bold: true, noIndent: true }),
      empty(),
      body("1. На дашборде нажмите кнопку «Создать курс» или перейдите в раздел «Мои курсы» → «+ Новый курс»."),
      empty(),
      body("2. Заполните форму: введите название курса (обязательно) и описание. Загрузите обложку курса (рекомендуемый размер 1280×720 px, форматы JPG/PNG/WebP). Нажмите «Сохранить»."),
      empty(),
      body("3. Курс создан в статусе «черновик» (isPublished = false) и недоступен студентам. Для публикации нажмите «Опубликовать» на странице редактирования курса."),
      empty(),
      body("Управление структурой курса", { bold: true, noIndent: true }),
      empty(),
      body("1. На странице курса нажмите «Редактировать» → откроется редактор структуры."),
      empty(),
      body("2. Для добавления модуля нажмите «+ Добавить модуль», введите название (например, «Основы Python», «Продвинутые темы»). Нажмите Enter или кнопку «Сохранить». Модуль появится в списке."),
      empty(),
      body("3. Для добавления занятия в модуль кликните на модуль, затем нажмите «+ Добавить занятие». Введите название занятия и выберите тип:"),
      bullet("Материал — текстовое занятие с Markdown-редактором."),
      bullet("Видео — занятие с видеоплеером (ссылка на YouTube или загруженный файл)."),
      bullet("Тест — занятие, состоящее только из теста без текстового материала."),
      bullet("Live-урок — занятие с расписанием, привязанное к видеозвонку."),
      empty(),
      body("4. Порядок модулей и занятий определяется полем position. Для изменения порядка воспользуйтесь кнопками перемещения вверх/вниз рядом с элементом."),
      empty(),
      body("Редактирование содержимого занятия", { bold: true, noIndent: true }),
      empty(),
      body("1. Кликните на занятие в структуре курса — откроется редактор юнита (UnitEditor)."),
      empty(),
      body("2. Текстовое поле поддерживает Markdown-синтаксис:"),
      bullet("# Заголовок 1, ## Заголовок 2 — заголовки разных уровней."),
      bullet("**жирный**, *курсив* — форматирование текста."),
      bullet("- пункт 1 — маркированный список."),
      bullet("```код``` — блок кода с подсветкой синтаксиса."),
      bullet("![Описание](url) — встроенное изображение."),
      empty(),
      body("3. Для вставки изображения непосредственно в текст: поставьте курсор в нужное место текста, нажмите кнопку «Вставить картинку». Откроется диалог выбора файла. После загрузки Markdown-строка ![название](url) будет автоматически вставлена в позицию курсора."),
      empty(),
      body("4. Для прикрепления документа (PDF, Word, Excel и др.) используйте раздел «Файлы» под текстовым полем: перетащите файл или нажмите «Загрузить файл». Файл будет показан студентам как ссылка для скачивания с именем и размером."),
      empty(),
      body("5. Для добавления видео введите URL в поле «Ссылка на видео» — поддерживаются YouTube, Vimeo и прямые ссылки на видеофайлы."),
      empty(),
      body("6. Нажмите «Сохранить» для применения изменений."),
      empty(),
      body("Создание теста", { bold: true, noIndent: true }),
      empty(),
      body("1. В редакторе юнита перейдите на вкладку «Тесты». Нажмите «Добавить тест», введите название."),
      empty(),
      body("2. Нажмите «Добавить вопрос». Выберите тип вопроса:"),
      bullet("Одиночный выбор — один правильный ответ из нескольких вариантов."),
      bullet("Множественный выбор — несколько правильных ответов."),
      bullet("Открытый ответ — студент вводит текст, преподаватель проверяет вручную."),
      empty(),
      body("3. Введите текст вопроса. Для вопросов с вариантами ответа добавьте не менее двух вариантов и отметьте правильный(е) флажком «Верный ответ». Установите количество баллов за вопрос (по умолчанию 1)."),
      empty(),
      body("4. Для открытых вопросов заполните поле «Эталонный ответ» — студент увидит его после сдачи как образец."),
      empty(),
      body("5. Нажмите «Сохранить тест». Тест будет доступен студентам при следующем открытии страницы занятия."),
      empty(),
      body("Просмотр статистики курса", { bold: true, noIndent: true }),
      empty(),
      body("1. На странице курса нажмите «Статистика курса» — откроется /courses/[id]/stats."),
      empty(),
      body("2. Сводная таблица студентов содержит следующие колонки: имя и email студента, общий прогресс курса (%), тесты (сдано / всего), средний балл по тестам, домашние задания (проверено / всего)."),
      empty(),
      body("3. Правее таблицы находятся карточки с агрегированной статистикой по тестам и домашним заданиям курса: процент прохождения, средние баллы, количество незавершённых работ."),
      empty(),
      body("4. Нажмите на строку студента в таблице — откроется детальная страница /courses/[id]/stats/[studentId]."),
      empty(),
      body("5. На детальной странице в разделе «Занятия» статус каждого занятия обозначен:"),
      bullet("Зелёный круг с галочкой — занятие завершено (COMPLETED), указана дата завершения."),
      bullet("Оранжевый круг — занятие в процессе (IN_PROGRESS), указан процент и дата начала."),
      bullet("Серый круг — занятие ещё не открывалось."),
      empty(),
      body("6. В разделе «Тесты» для каждой попытки отображается: дата сдачи, балл (например, «17 / 20»), детальный разбор с цветовой подсветкой ответов."),
      empty(),
      body("Проверка домашних заданий", { bold: true, noIndent: true }),
      empty(),
      body("1. На детальной странице статистики студента найдите раздел «Домашние задания»."),
      empty(),
      body("2. Для каждого задания отображаются: название, дата отправки, текст ответа студента, текущий статус."),
      empty(),
      body("3. Для непроверенных работ (статус submitted) нажмите «Проверить ДЗ»."),
      empty(),
      body("4. Введите оценку (число от 0 до 100) и письменный комментарий с разбором ошибок и рекомендациями."),
      empty(),
      body("5. Нажмите «Сохранить оценку». Статус изменится на reviewed. Студент получит уведомление и сможет просмотреть результат на странице занятия."),
      empty(),
      caption("Рис. 9 – Редактор занятия: Markdown-редактор, вкладки файлов и тестов"),
      empty(),

      heading2("Проведение видеозанятия", "3.4"),
      empty(),
      body("Групповое занятие (привязанное к курсу)", { bold: true, noIndent: true }),
      empty(),
      body("1. В разделе «Расписание» дашборда нажмите «Создать занятие». Введите название, выберите курс, укажите дату и время начала, длительность в минутах."),
      empty(),
      body("2. В запланированное время перейдите на страницу занятия в дашборде, нажмите «Начать занятие». Откроется страница видеокомнаты. Браузер запросит разрешение на доступ к камере и микрофону — нажмите «Разрешить»."),
      empty(),
      body("3. Студенты, записанные на курс, увидят предстоящее занятие на своём дашборде и смогут перейти по ссылке в указанное время."),
      empty(),
      body("4. В комнате доступны: плитки видео всех участников, кнопка выключения микрофона, кнопка выключения камеры, демонстрация экрана, текстовый чат внутри занятия."),
      empty(),
      body("5. Для завершения занятия нажмите «Завершить урок» → «Подтвердить». Все участники будут отключены."),
      empty(),
      body("Персональный видеозвонок (один на один)", { bold: true, noIndent: true }),
      empty(),
      body("1. В дашборде перейдите в раздел «Звонки» → «Пригласить студента». Введите имя студента (система найдёт по email)."),
      empty(),
      body("2. Укажите тему встречи и нажмите «Создать приглашение». Система сгенерирует уникальную ссылку вида /calls/invite/[token]."),
      empty(),
      body("3. Скопируйте ссылку и отправьте студенту (через сообщения платформы или любой мессенджер)."),
      empty(),
      body("4. Студент переходит по ссылке, видит страницу с темой встречи и нажимает «Присоединиться». Оба участника попадают в видеокомнату."),
      empty(),
      body("5. Во время звонка доступна совместная интерактивная доска: нажмите кнопку «Доска» в интерфейсе. Оба участника могут рисовать, писать и строить схемы одновременно. Состояние доски автоматически сохраняется."),
      empty(),
      caption("Рис. 10 – Видеокомната: плитки участников, чат, кнопки управления"),
      empty(),

      heading2("Личный кабинет и уведомления", "3.5"),
      empty(),
      body("Личный кабинет", { bold: true, noIndent: true }),
      empty(),
      body("Перейдите в /profile или нажмите на иконку аккаунта в шапке сайта. Личный кабинет содержит:"),
      bullet("Раздел «Профиль»: изменение отображаемого имени, загрузка аватара."),
      bullet("Раздел «Безопасность»: смена email (требует подтверждения нового адреса), смена пароля (требует ввода текущего), удаление аккаунта (необратимое действие)."),
      bullet("Раздел «Уведомления»: настройка способов получения уведомлений."),
      empty(),
      body("Система уведомлений", { bold: true, noIndent: true }),
      empty(),
      body("Иконка колокольчика в шапке сайта (NotificationBell.tsx) отображает счётчик непрочитанных уведомлений. При нажатии открывается выпадающий список последних уведомлений. Кликом по уведомлению открывается соответствующая страница (занятие, тест, домашнее задание). Уведомления генерируются при:"),
      bullet("Проверке домашнего задания преподавателем — студент видит оценку и комментарий."),
      bullet("Записи нового студента на курс — преподаватель видит уведомление."),
      bullet("Начале запланированного занятия — напоминание за 15 минут до старта."),
      empty(),
      caption("Рис. 11 – Личный кабинет: разделы «Профиль», «Безопасность», «Уведомления»"),
      empty(),

      // ── ЗАКЛЮЧЕНИЕ ──────────────────────────────
      pageBreak(),
      centered("ЗАКЛЮЧЕНИЕ", { size: SIZE_BODY, bold: true, underline: true }),
      empty(),
      body("В ходе выполнения данного проекта была разработана полнофункциональная платформа для онлайн-обучения «SkillHub», обеспечивающая полный цикл взаимодействия преподавателя и студента в цифровой образовательной среде."),
      empty(),
      body("Технологические результаты проекта", { bold: true, noIndent: true }),
      empty(),
      body("Реализована многоролевая веб-система на стеке Next.js 16 + TypeScript + Prisma + PostgreSQL (Neon) с задеплоенным приложением на Vercel. База данных содержит 18 таблиц, связанных внешними ключами, с каскадным удалением и оптимизированными составными индексами. API-слой включает более 40 Route Handler-ов, покрывающих все аспекты работы платформы."),
      empty(),
      body("Функциональные результаты", { bold: true, noIndent: true }),
      empty(),
      bullet("Реализована система аутентификации с разграничением прав по трём ролям (STUDENT, TEACHER, ADMIN) на основе JWT-токенов."),
      bullet("Создан гибкий редактор курсов с поддержкой иерархии «курс → модуль → занятие», четырёх типов юнитов, Markdown-редактора с вставкой изображений в позицию курсора, загрузки файловых вложений."),
      bullet("Разработана система тестирования с тремя типами вопросов (одиночный/множественный выбор, открытый ответ), автопроверкой закрытых вопросов, ручной проверкой открытых, детальным разбором попыток с цветовой подсветкой ответов."),
      bullet("Реализована двухуровневая система прогресса: мгновенное обновление через localStorage с fire-and-forget синхронизацией в PostgreSQL, подписки на события storage/focus/visibilitychange для синхронизации между вкладками."),
      bullet("Разработана детальная аналитика для преподавателя: сводная таблица студентов, статистика по тестам и домашним заданиям, детальная страница конкретного студента с полным разбором его активности."),
      bullet("Интегрированы видеозвонки в реальном времени на базе LiveKit WebRTC в двух форматах: групповые занятия курса и персональные сессии «один на один» с invite-токенами."),
      bullet("Реализована совместная интерактивная доска (BoardDocument) с персистентным JSON-состоянием для пар преподаватель–студент."),
      bullet("Реализована система домашних заданий с отслеживанием статуса сдачи, оценкой (0–100) и письменными комментариями преподавателя."),
      bullet("Разработана система уведомлений с колокольчиком в шапке сайта и счётчиком непрочитанных сообщений."),
      empty(),
      body("Образовательный контекст", { bold: true, noIndent: true }),
      empty(),
      body("В ходе работы над проектом были освоены и применены на практике: архитектурный паттерн Feature-Sliced Design в контексте Next.js App Router, разработка серверных и клиентских компонентов React, типобезопасная работа с базой данных через Prisma ORM, реализация REST API с авторизацией, интеграция WebRTC через LiveKit SDK, двухуровневые стратегии хранения состояния, настройка CI/CD и управление переменными окружения в облачной инфраструктуре."),
      empty(),
      body("Перспективы развития платформы", { bold: true, noIndent: true }),
      empty(),
      body("Дальнейшее развитие SkillHub может включать следующие направления:"),
      bullet("Платёжный шлюз для монетизации курсов (Stripe или ЮKassa): платные курсы с управлением подписками и выплатами преподавателям."),
      bullet("Система сертификатов: автоматическая выдача PDF-сертификата при 100%-м прохождении курса с уникальным кодом верификации."),
      bullet("Мобильное приложение на React Native с поддержкой оффлайн-режима для изучения материалов без интернета."),
      bullet("AI-ассистент: интеграция Claude API для генерации персонализированных подсказок к тестовым вопросам и автоматической проверки открытых ответов."),
      bullet("Расширенная аналитика: тепловые карты активности, воронки вовлечённости, A/B-тестирование образовательного контента."),
      bullet("Форумы и комментарии к урокам: элементы социального обучения для создания сообщества вокруг курсов."),
      empty(),
      body("Разработанная платформа SkillHub демонстрирует эффективность выбранного технологического стека для создания полнофункциональных образовательных систем. Использование Next.js App Router с серверными компонентами, Prisma ORM и serverless-инфраструктуры Vercel + Neon обеспечивает высокую производительность, типобезопасность и простоту масштабирования при росте числа пользователей и объёма контента."),

      // ── ПРИЛОЖЕНИЕ ──────────────────────────────
      pageBreak(),
      centered("ПРИЛОЖЕНИЕ", { size: SIZE_BODY, bold: true, underline: true }),
      empty(),
      body("Приложение А. Полная схема перечислений базы данных (prisma/schema.prisma)", { bold: true, noIndent: true }),
      empty(),
      codeBlock([
        'enum Role          { ADMIN  TEACHER  STUDENT }',
        'enum UnitType      { MATERIAL  VIDEO  TEST  LIVE }',
        'enum TestQuestionType { SINGLE  MULTI  OPEN }',
        'enum CallStatus    { SCHEDULED  ACTIVE  ENDED  CANCELLED }',
        'enum UnitProgressStatus { IN_PROGRESS  COMPLETED }',
        'enum AttachmentType { FILE  IMAGE }',
      ]),
      empty(),
      body("Приложение Б. Модель пользователя и курса (prisma/schema.prisma)", { bold: true, noIndent: true }),
      empty(),
      codeBlock([
        'model User {',
        '  id             String               @id @default(cuid())',
        '  name           String',
        '  email          String               @unique',
        '  passwordHash   String',
        '  role           Role                 @default(STUDENT)',
        '  createdAt      DateTime             @default(now())',
        '  updatedAt      DateTime             @updatedAt',
        '  enrollments    Enrollment[]',
        '  taughtCourses  Course[]             @relation("TeacherCourses")',
        '  unitProgress   UnitProgress[]',
        '  testAttempts   TestAttempt[]',
        '  testAnswers    TestAnswer[]         @relation("TestAnswerAuthor")',
        '  submissions    HomeworkSubmission[]',
        '  taughtCalls    CallSession[]        @relation("CallTeacher")',
        '  studentCalls   CallSession[]        @relation("CallStudent")',
        '  boardAsTeacher BoardDocument[]      @relation("BoardTeacher")',
        '  boardAsStudent BoardDocument[]      @relation("BoardStudent")',
        '}',
        '',
        'model Course {',
        '  id          String         @id @default(cuid())',
        '  title       String',
        '  description String',
        '  teacherId   String',
        '  createdAt   DateTime       @default(now())',
        '  updatedAt   DateTime       @updatedAt',
        '  teacher     User           @relation("TeacherCourses",',
        '                fields: [teacherId], references: [id], onDelete: Cascade)',
        '  modules     CourseModule[]',
        '  enrollments Enrollment[]',
        '  homeworks   Homework[]',
        '  tests       Test[]',
        '  unitProgress UnitProgress[]',
        '}',
      ]),
      empty(),
      body("Приложение В. Хук useCourseProgress — синхронизация прогресса", { bold: true, noIndent: true }),
      empty(),
      codeBlock([
        'function syncProgressToDb(',
        '  unitId: string,',
        '  status: "in_progress" | "completed",',
        '  progressPercent: number,',
        ') {',
        '  fetch(`/api/units/${unitId}/progress`, {',
        '    method: "PATCH",',
        '    headers: { "Content-Type": "application/json" },',
        '    body: JSON.stringify({ status, progressPercent }),',
        '  }).catch(() => null); // fire-and-forget',
        '}',
        '',
        '// При завершении занятия:',
        'const markCompleted = useCallback((unitId: string) => {',
        '  const result = markUnitCompleted(courseId, unitId); // запись в localStorage',
        '  syncProgressToDb(unitId, "completed", 100);         // синхронизация с БД',
        '  refresh();                                          // перерендер UI',
        '  return result;',
        '}, [courseId, refresh]);',
      ]),
      empty(),
      body("Приложение Г. API-маршрут сохранения прогресса (src/app/api/units/[unitId]/progress/route.ts)", { bold: true, noIndent: true }),
      empty(),
      codeBlock([
        'export async function PATCH(',
        '  request: Request,',
        '  { params }: { params: Promise<{ unitId: string }> },',
        ') {',
        '  const user = await getSessionUser();',
        '  if (!user)',
        '    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });',
        '',
        '  const { unitId } = await params;',
        '  const unit = await db.lessonUnit.findUnique({',
        '    where: { id: unitId },',
        '    select: { id: true, module: { select: { courseId: true } } },',
        '  });',
        '  if (!unit)',
        '    return NextResponse.json({ error: "Not found" }, { status: 404 });',
        '',
        '  const { status, progressPercent } = await request.json();',
        '  const dbStatus = status === "completed"',
        '    ? UnitProgressStatus.COMPLETED : UnitProgressStatus.IN_PROGRESS;',
        '  const pct = Math.max(0, Math.min(100, Math.round(progressPercent ?? 0)));',
        '',
        '  const record = await db.unitProgress.upsert({',
        '    where: { userId_unitId: { userId: user.id, unitId } },',
        '    create: {',
        '      userId: user.id, unitId,',
        '      courseId: unit.module.courseId,',
        '      status: dbStatus, progressPercent: pct,',
        '      startedAt: new Date(), lastVisitedAt: new Date(),',
        '    },',
        '    update: {',
        '      status: dbStatus, progressPercent: pct,',
        '      lastVisitedAt: new Date(),',
        '      completedAt: dbStatus === "COMPLETED" ? new Date() : undefined,',
        '    },',
        '  });',
        '  return NextResponse.json(record);',
        '}',
      ]),
      empty(),
      body("Приложение Д. Ссылки на использованные технологии", { bold: true, noIndent: true }),
      empty(),
      bullet("Next.js — https://nextjs.org/docs"),
      bullet("Prisma ORM — https://www.prisma.io/docs"),
      bullet("Neon PostgreSQL — https://neon.tech/docs"),
      bullet("LiveKit WebRTC — https://docs.livekit.io"),
      bullet("Tailwind CSS — https://tailwindcss.com/docs"),
      bullet("NextAuth.js — https://next-auth.js.org"),
      bullet("TypeScript — https://www.typescriptlang.org/docs"),
    ],
  }],
});

Packer.toBuffer(doc).then((buffer) => {
  writeFileSync("Отчет_SkillHub_Платформа_для_онлайн_обучения.docx", buffer);
  console.log("Done: Отчет_SkillHub_Платформа_для_онлайн_обучения.docx");
});
